### ISSUE TITLE
open and close events not firing?

### ISSUE THREAD

**Issue by jose-von-chong** [admob-plus/admob-plus#163]
Hi wanted to know what are the steps to fire the next events:
document.addEventListener('admob.interstitial.open', () => {})
document.addEventListener('admob.interstitial.close', () => {})

i´ve been trying test mode and production mode, debug and release APK. but neither event is firing.

**Comment by IsaaacD** [comment]
I've recently started getting this issue too, I've tried changing how I'm registering events and now doing so in the deviceready event. I do notice that there are some exceptions occurring a couple seconds after I close the ad. It makes me think it's attempting to fire the event but failing.
```
2020-07-04 07:04:13.831 22487-22633/io.cordova.netherassault W/ConnectionTracker: Exception thrown while unbinding
    java.lang.IllegalArgumentException: Service not registered: lq@677c6fc
        at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1766)
        at android.app.ContextImpl.unbindService(ContextImpl.java:1810)
        at android.content.ContextWrapper.unbindService(ContextWrapper.java:741)
        at cg.b(:com.google.android.gms.dynamite_measurementdynamite@202117081@20.21.17 (120400-0):1)
        at cg.a(:com.google.android.gms.dynamite_measurementdynamite@202117081@20.21.17 (120400-0):6)
        at lr.A(:com.google.android.gms.dynamite_measurementdynamite@202117081@20.21.17 (120400-0):10)
        at lc.a(:com.google.android.gms.dynamite_measurementdynamite@202117081@20.21.17 (120400-0):3)
        at dz.run(:com.google.android.gms.dynamite_measurementdynamite@202117081@20.21.17 (120400-0):3)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at iy.run(:com.google.android.gms.dynamite_measurementdynamite@202117081@20.21.17 (120400-0):6)
```

Any ideas anyone?

**Comment by IsaaacD** [comment]
I think I figured it out. 

I was loading a new interstitial ad when I was serving up an already loaded interstitial ad and somehow (bug?) it stopped the event from triggering and threw the above error. I now load a new interstitial ad in the 'admob.interstitial.load_fail' and 'admob.interstitial.close' events, and it's working.
