### ISSUE TITLE
The platform "flutter_app" error while trying to install

### ISSUE THREAD

**Issue by merbin2012** [admob-plus/admob-plus#173]
When I add this the following error showing

`Installing "cordova-admob-plus" for flutter_app
Unable to load PlatformApi from platform. Error: Cannot find module 'C:\Android\cordova projects\ANDROID\learnshortcutkeyapp2\platforms\flutter_app\cordova\Api.js'
Require stack:
- C:\Users\Merbin Joe\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\cordova\util.js
- C:\Users\Merbin Joe\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\platforms\platforms.js
- C:\Users\Merbin Joe\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js
- C:\Users\Merbin Joe\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\plugman.js
- C:\Users\Merbin Joe\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\cordova-lib.js
- C:\Users\Merbin Joe\AppData\Roaming\npm\node_modules\cordova\src\help.js
- C:\Users\Merbin Joe\AppData\Roaming\npm\node_modules\cordova\src\cli.js
- C:\Users\Merbin Joe\AppData\Roaming\npm\node_modules\cordova\bin\cordova
Failed to install 'cordova-admob-plus': Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('The platform "flutter_app" does not appear to be a valid cordova platform. It is missing API.js. flutter_app not supported.')
    at CordovaEventEmitter.emit (events.js:198:17)
    at CordovaEventEmitter.emit (C:\Users\Merbin Joe\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-common\src\events.js:69:22)
    at Object.getPlatformApiFunction (C:\Users\Merbin Joe\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\cordova\util.js:384:20)
    at Object.getPlatformApi (C:\Users\Merbin Joe\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\platforms\platforms.js:55:32)
    at handleInstall (C:\Users\Merbin Joe\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:580:29)
    at C:\Users\Merbin Joe\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:349:28
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Unhandled error. ('The platform "flutter_app" does not appear to be a valid cordova platform. It is missing API.js. flutter_app not supported.')`

**Comment by MilkyWayGalaxyUser** [comment]
adding cordova to flutter what?
