### ISSUE TITLE
[Android] App crash on startup

### ISSUE THREAD

**Issue by svzi** [admob-plus/admob-plus#24]
Sadly my Ionic 3 app doesn't only crash on iOS during startup (see https://github.com/admob-plus/admob-plus/issues/23), but also on Android as well. Following the important part from system logs:

```
 E  java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.Ille
     galStateException:
 E  ******************************************************************************
 E  * The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
 E  * should follow the instructions here: https://goo.gl/fQ2neu to add a valid  *
 E  * App ID inside the AndroidManifest. Google Ad Manager publishers should     *
 E  * follow instructions here: https://goo.gl/h17b6x.                           *
 E  ******************************************************************************
 E      at android.app.ActivityThread.installProvider(ActivityThread.java:5855)
 E      at android.app.ActivityThread.installContentProviders(ActivityThread.java:5444)
 E      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5383)
 E      at android.app.ActivityThread.-wrap2(ActivityThread.java)
 E      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1541)
 E      at android.os.Handler.dispatchMessage(Handler.java:102)
 E      at android.os.Looper.loop(Looper.java:154)
 E      at android.app.ActivityThread.main(ActivityThread.java:6123)
 E      at java.lang.reflect.Method.invoke(Native Method)
 E      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
 E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
 E  Caused by: java.lang.IllegalStateException:
 E  ******************************************************************************
 E  * The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
 E  * should follow the instructions here: https://goo.gl/fQ2neu to add a valid  *
 E  * App ID inside the AndroidManifest. Google Ad Manager publishers should     *
 E  * follow instructions here: https://goo.gl/h17b6x.                           *
 E  ******************************************************************************
 E      at com.google.android.gms.internal.ads.zzmn.attachInfo(Unknown Source)
 E      at com.google.android.gms.ads.MobileAdsInitProvider.attachInfo(Unknown Source)
 E      at android.app.ActivityThread.installProvider(ActivityThread.java:5852)
 E      ... 10 more
```

So it looks like the initialization while adding the plugin didn't do well, but I the terminal didn't show any error messages!

Part of my `config.xml`:
```
    <plugin name="cordova-admob-plus" spec="0.6.0">
        <variable name="APP_ID_ANDROID" value="ca-app-pub-123~456" />
        <variable name="APP_ID_IOS" value="ca-app-pub-456~789" />
    </plugin>
```

Some project / system information:

```
 ~> ionic info
✔ Gathering environment info - done!

Ionic:

   ionic (Ionic CLI)  : 4.2.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.0.0, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic 5.1.2, cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.2.0, (and 23 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/svzi/Library/Android/sdk)
   ios-deploy        : 1.9.2
   NodeJS            : v8.11.3 (/usr/local/bin/node)
   npm               : 5.6.0
   OS                : macOS High Sierra
   Xcode             : Xcode 10.0 Build version 10A255
```

Any help would be really much appreciated!

Best,
Sven

**Comment by svzi** [comment]
I've updated https://github.com/admob-plus/admob-plus/issues/23 to reflect iOS and Android issues on startup. So I will close this issue.
