### ISSUE TITLE
Build error (pod: Command failed with exit code 1)

### ISSUE THREAD

**Issue by aenima86** [admob-plus/admob-plus#249]
Hi all

I cant build my project when the plugin is included.

I get this error:

[16:56:16] Failed to install 'cordova-admob-plus': Error: pod: Command failed with exit code 1
[16:56:16]     at ChildProcess.whenDone (/private/tmp/download/node_modules/cordova-common/src/superspawn.js:136:25)
[16:56:16]     at ChildProcess.emit (events.js:315:20)
[16:56:16]     at maybeClose (internal/child_process.js:1021:16)
[16:56:16]     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
[16:56:16] pod: Command failed with exit code 1

The building environment is
monaca.io
[16:54:55] + npm -v
[16:54:55] 6.14.6
[16:54:55] + cordova -v
[16:54:57] 10.0.0
[16:54:57] + pod --version
[16:55:09] 1.9.1
[16:55:09] + xcodebuild -version
[16:55:09] Xcode 11.3

log: https://pastebin.com/NAwWGp8k

Any good ideas would be very appreciated:)

**Comment by ratson** [comment]
@aenima86 What is your output of `pod spec cat Google-Mobile-Ads-SDK`?

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
`[16:56:16] Failed to install 'cordova-admob-plus': Error: pod: Command failed with exit code 1`

You are querying the `alpha` of this plug-in with `cordova-admob-plus` .

Try to switch to the `beta` version, using `admob-plus-cordova`.

**Comment by aenima86** [comment]
ty, it helped to switch to Xcode 12 :)

**Comment by Mr-Anonymous** [comment]
I had the same issue. I have Xcode 13 and its not the issue. Also `pod repo update` did not solve it. In the end, I found out it has to do the version of pod installed. So I updated cocapods to the latest version using `sudo gem install cocoapods` and after that building ios app worked with no `exit code 1` error.
