### ISSUE TITLE
Android crash reports: admob.plugin.ads.InterstitialAd cannot be cast to admob.plugin.ads.BannerAd

### ISSUE THREAD

**Issue by tominou** [admob-plus/admob-plus#262]
Hi,

I receive many identical crash reports from Firebase, here is it:

```
Fatal Exception: java.lang.ClassCastException: admob.plugin.ads.InterstitialAd cannot be cast to admob.plugin.ads.BannerAd
       at admob.plugin.ads.BannerAd.getOrCreate(BannerAd.java:32)
       at admob.plugin.AdMob$2.run(AdMob.java:115)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
```

Thank you in advance

**Comment by ratson** [comment]
@tominou You are using an old version of the plugin, update to the latest version may fix it.

**Comment by tominou** [comment]
Indeed it wasn't the latest version.

However, after upgrading I think I get similar reports:
```
Fatal Exception: java.lang.ClassCastException: Cannot cast admob.plugin.ads.Interstitial to admob.plugin.ads.Banner
       at java.lang.Class.cast(Class.java:2446)
       at admob.plugin.ExecuteContext.optAdOrCreate(ExecuteContext.java:59)
       at admob.plugin.AdMob.lambda$executeBannerShow$1(AdMob.java:112)
       at admob.plugin.-$$Lambda$AdMob$_6vSUdIgF7xLxcp85eVyVZwturw.run(:2)
       at android.os.Handler.handleCallback(:2)
       at android.os.Handler.dispatchMessage(:4)
       at android.os.Looper.loop(:242)
       at android.app.ActivityThread.main(:98)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(:11)
       at com.android.internal.os.ZygoteInit.main(:275)
```
Thank you in advance

**Comment by ratson** [comment]
@tominou Would post your code how to create the ads? The error indicates that you passing the wrong id to native call.
