### ISSUE TITLE
Errors are thrown when installing admob-plus-cordova due to missing module 'properties-parser'

### ISSUE THREAD

**Issue by cauboy** [admob-plus/admob-plus#316]
**Describe the bug**
The plugin cannot be installed due to missing module `Error: Cannot find module 'properties-parser'`

When installing the module (`npm install -D properties-parser`) before running the install command, everything is fine.

**To Reproduce**
Run the install command from the docs:

```bash
# Run following command
cordova plugin add admob-plus-cordova --save --variable APP_ID_ANDROID=ca-app-pub-xxx~yyy --variable APP_ID_IOS=ca-app-pub-xxx~zzz

(node:7975) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7975) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'find' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'head' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'set' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'test' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'to' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'which' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'find' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'head' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'set' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'test' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'to' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency
(node:7975) Warning: Accessing non-existent property 'which' of module exports inside circular dependency
Installing "admob-plus-cordova" for android
Failed to install 'admob-plus-cordova': Error: /Users/my-cordova-app/platforms/android/cordova/version: Command failed with exit code 1 Error output:
internal/modules/cjs/loader.js:1032
  throw err;
  ^

Error: Cannot find module 'properties-parser'
Require stack:
- /Users/my-cordova-app/platforms/android/cordova/lib/AndroidProject.js
- /Users/my-cordova-app/platforms/android/cordova/Api.js
- /Users/my-cordova-app/platforms/android/cordova/version
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/Users/my-cordova-app/platforms/android/cordova/lib/AndroidProject.js:22:25)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/my-cordova-app/platforms/android/cordova/lib/AndroidProject.js',
    '/Users/my-cordova-app/platforms/android/cordova/Api.js',
    '/Users/my-cordova-app/platforms/android/cordova/version'
  ]
}
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1051:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
Error: /Users/my-cordova-app/platforms/android/cordova/version: Command failed with exit code 1 Error output:
internal/modules/cjs/loader.js:1032
  throw err;
  ^

Error: Cannot find module 'properties-parser'
Require stack:
- /Users/my-cordova-app/platforms/android/cordova/lib/AndroidProject.js
- /Users/my-cordova-app/platforms/android/cordova/Api.js
- /Users/my-cordova-app/platforms/android/cordova/version
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/Users/my-cordova-app/platforms/android/cordova/lib/AndroidProject.js:22:25)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/my-cordova-app/platforms/android/cordova/lib/AndroidProject.js',
    '/Users/my-cordova-app/platforms/android/cordova/Api.js',
    '/Users/my-cordova-app/platforms/android/cordova/version'
  ]
```

**Expected behavior**
I expect the plugin being installed without errors

**Environment**

```
(paste the output of the command here)
```

**Comment by CaturViriyananda** [comment]
try `npm install properties-parser`

**Comment by cauboy** [comment]
@CaturViriyananda thanks, that's what I've done to fix it. 

I was mentioning that, b/c  if the plugin requires `properties-parser` it should be part of the required dependencies.

**Comment by CaturViriyananda** [comment]
i once was also had similar issue take a look here #290 
i installed the required module locally instead of globally that previously wont fix my issue

**Comment by ratson** [comment]
@cauboy What is your npm version?
