### ISSUE TITLE
Banner offset keep stopping

### ISSUE THREAD

**Issue by EMI-INDO** [admob-plus/admob-plus#319]
Hi, friend?

If using the offset banner the app keeps stopping.

### PLAY_SERVICES_VERSION: 19.8.0

cordova plugin add admob-plus-cordova@1.7.1 --save --variable APP_ID_ANDROID=ca-app-pub-3940256099942544~3347511713

### detail
CORDOVA CLI: 10.0.0
CORDOVA ANDROID : 9.0.0

### sample code
[index.zip](https://github.com/admob-plus/admob-plus/files/6386685/index.zip)

### 2 app-debug-offset-AND-NO-offset.apk 
[2-app-debug.zip](https://github.com/admob-plus/admob-plus/files/6386706/2-app-debug.zip)

### If using the offset banner
Click 2x button banner show the app keeps stopping.

### thank you

**Comment by ollm** [comment]
I have the same problem and I am using the latest version of the plugin (admob-plus-cordova@1.8.0), I think it is related to this https://github.com/admob-plus/admob-plus/issues/304

One way to make it happen is to call twice to `banner.show()`

**log calling twice to `banner.show()`:**

```
2021-04-29 16:44:07.018 13549-13549/mx.name.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: mx.name.app, PID: 13549
    java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
        at android.view.ViewGroup.addViewInner(ViewGroup.java:5233)
        at android.view.ViewGroup.addView(ViewGroup.java:5062)
        at android.view.ViewGroup.addView(ViewGroup.java:5034)
        at admob.plugin.ads.Banner.addBannerViewWithRelativeLayout(Banner.java:306)
        at admob.plugin.ads.Banner.addBannerView(Banner.java:232)
        at admob.plugin.ads.Banner.show(Banner.java:136)
        at admob.plugin.AdMob.lambda$executeBannerShow$2(AdMob.java:132)
        at admob.plugin.-$$Lambda$AdMob$beAtfZTpJUNpk8W7kl8cHhoJKyk.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7858)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:984)
```

**Firebase log (Production):**

```
Fatal Exception: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
       at android.view.ViewGroup.addViewInner(ViewGroup.java:5958)
       at android.view.ViewGroup.addView(ViewGroup.java:5777)
       at android.view.ViewGroup.addView(ViewGroup.java:5749)
       at admob.plugin.ads.Banner.addBannerViewWithRelativeLayout(Banner.java:306)
       at admob.plugin.ads.Banner.addBannerView(Banner.java:232)
       at admob.plugin.ads.Banner.show(Banner.java:136)
       at admob.plugin.AdMob.lambda$executeBannerShow$2(AdMob.java:132)
       at admob.plugin.-$$Lambda$AdMob$beAtfZTpJUNpk8W7kl8cHhoJKyk.run(:2)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8107)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```
