### ISSUE TITLE
"admob-plus-cordova" addBannerViewWithLinearLayout sometimes throw  java.lang.StackOverflowError

### ISSUE THREAD

**Issue by victorvhpg** [admob-plus/admob-plus#327]
After updated the plugin, i have a lot of erros 

I using latest version "admob-plus-cordova": "^1.9.0",

```
  Fatal Exception: java.lang.StackOverflowError: stack size 8192KB
       at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:8837)
       at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:8839)
       at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:8839)
       at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:8839)
       at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:8839)
       at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:8839)
       at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:8839)
       at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:8839)
       at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:8839)
       at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:8839)
       at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:8839)
       at android.view.View.resetRtlProperties(View.java:21511)
       at android.view.ViewGroup.addViewInner(ViewGroup.java:6116)
       at android.view.ViewGroup.addView(ViewGroup.java:5884)
       at android.view.ViewGroup.addView(ViewGroup.java:5824)
       at android.view.ViewGroup.addView(ViewGroup.java:5796)
       at admob.plugin.ads.Banner.addBannerViewWithLinearLayout(Banner.java:301)
       at admob.plugin.ads.Banner.addBannerView(Banner.java:271)
       at admob.plugin.ads.Banner.reloadBannerView(Banner.java:212)
       at admob.plugin.ads.Banner.onConfigurationChanged(Banner.java:197)
       at admob.plugin.AdMob.onConfigurationChanged(AdMob.java:204)
       at org.apache.cordova.PluginManager.onConfigurationChanged(PluginManager.java:509)
       at org.apache.cordova.CordovaActivity.onConfigurationChanged(CordovaActivity.java:495)
       at android.app.ActivityThread.performActivityConfigurationChanged(ActivityThread.java:6248)
       at android.app.ActivityThread.performConfigurationChangedForActivity(ActivityThread.java:6074)
       at android.app.ActivityThread.performConfigurationChangedForActivity(ActivityThread.java:6052)
       at android.app.ActivityThread.handleActivityConfigurationChanged(ActivityThread.java:6662)
       at android.app.servertransaction.ActivityConfigurationChangeItem.execute(ActivityConfigurationChangeItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8506)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by ratson** [comment]
@victorvhpg Would you check if `1.9.1` fixes the issue?

**Comment by victorvhpg** [comment]
> @victorvhpg Would you check if `1.9.1` fixes the issue?

thanks, but now the banner doesn't show
I think there a bug here:
```
    private void addBannerView() {
        Objects.requireNonNull(mAdView);
        if (this.offset == null) {
            if (getParentView(mAdView) == rootLinearLayout) return;
            addBannerViewWithLinearLayout();
        } else {
            if (getParentView(mAdView) == mRelativeLayout) return;
            addBannerViewWithRelativeLayout();
        }
    }
```
the first time that show banner,  getParentView(mAdView)  is null  and rootLinearLayout is null too
then addBannerViewWithLinearLayout never was called

**Comment by ratson** [comment]
@victorvhpg Would you try again with `1.9.2`?

**Comment by victorvhpg** [comment]
> @victorvhpg Would you try again with `1.9.2`?
@ratson 
the error still happens, but now on line 291
```
Fatal Exception: java.lang.StackOverflowError: stack size 8MB
       at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7022)
       at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7023)
       at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7023)
       at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7023)
       at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7023)
       at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7023)
       at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7023)
       at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7023)
       at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7023)
       at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7023)
       at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7023)
       at android.view.View.resetRtlProperties(View.java:15434)
       at android.view.ViewGroup.addViewInner(ViewGroup.java:4706)
       at android.view.ViewGroup.addView(ViewGroup.java:4495)
       at android.view.ViewGroup.addView(ViewGroup.java:4436)
       at android.view.ViewGroup.addView(ViewGroup.java:4409)
`       at admob.plugin.ads.Banner.addBannerViewWithLinearLayout(Banner.java:291)`
       at admob.plugin.ads.Banner.addBannerView(Banner.java:260)
       at admob.plugin.ads.Banner.reloadBannerView(Banner.java:205)
       at admob.plugin.ads.Banner.onConfigurationChanged(Banner.java:192)
       at admob.plugin.AdMob.onConfigurationChanged(AdMob.java:204)
       at org.apache.cordova.PluginManager.onConfigurationChanged(PluginManager.java:509)
       at org.apache.cordova.CordovaActivity.onConfigurationChanged(CordovaActivity.java:495)
       at android.app.ActivityThread.performConfigurationChanged(ActivityThread.java:5611)
       at android.app.ActivityThread.handleConfigurationChanged(ActivityThread.java:5875)
       at android.app.ActivityThread.handleConfigurationChanged(ActivityThread.java:5729)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1944)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7406)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```


<img width="1557" alt="Screen Shot 2021-05-03 at 10 47 59" src="https://user-images.githubusercontent.com/333451/116884488-2a519f80-abfd-11eb-8915-b066ba691a40.png">

**Comment by ratson** [comment]
@victorvhpg I am not sure if `1.10.0` fixes the issue.
It would be great if you could pin point how the exception is occurred for me to debug.

**Comment by victorvhpg** [comment]
> @victorvhpg I am not sure if `1.10.0` fixes the issue.
> It would be great if you could pin point how the exception is occurred for me to debug.


@ratson  the bug still happens 

```
Fatal Exception: java.lang.StackOverflowError: stack size 8192KB
       at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7717)
       at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7719)
       at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7719)
       at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7719)
       at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7719)
       at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7719)
       at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7719)
       at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7719)
       at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7719)
       at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7719)
       at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7719)
       at android.view.View.resetRtlProperties(View.java:19378)
       at android.view.ViewGroup.addViewInner(ViewGroup.java:5325)
       at android.view.ViewGroup.addView(ViewGroup.java:5089)
       at android.view.ViewGroup.addView(ViewGroup.java:5029)
       at android.view.ViewGroup.addView(ViewGroup.java:5002)
       at admob.plugin.ads.Banner.addBannerViewWithLinearLayout(Banner.java:293)
       at admob.plugin.ads.Banner.addBannerView(Banner.java:262)
       at admob.plugin.ads.Banner.reloadBannerView(Banner.java:207)
       at admob.plugin.ads.Banner.lambda$onConfigurationChanged$0$Banner(Banner.java:193)
       at admob.plugin.ads.-$$Lambda$Banner$gu39PmGBD_ZqqbEjUZnsH3Okt0Y.run(:2)
       at android.app.Activity.runOnUiThread(Activity.java:7068)
       at admob.plugin.ads.Banner.onConfigurationChanged(Banner.java:192)
       at admob.plugin.AdMob.onConfigurationChanged(AdMob.java:204)
       at org.apache.cordova.PluginManager.onConfigurationChanged(PluginManager.java:509)
       at org.apache.cordova.CordovaActivity.onConfigurationChanged(CordovaActivity.java:495)
       at android.app.ActivityThread.performActivityConfigurationChanged(ActivityThread.java:5888)
       at android.app.ActivityThread.performConfigurationChangedForActivity(ActivityThread.java:5747)
       at android.app.ActivityThread.performConfigurationChangedForActivity(ActivityThread.java:5725)
       at android.app.ActivityThread.handleActivityConfigurationChanged(ActivityThread.java:6156)
       at android.app.servertransaction.ActivityConfigurationChangeItem.execute(ActivityConfigurationChangeItem.java:48)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:140)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:100)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2230)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7817)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1027)
```

**Comment by victorvhpg** [comment]
if my  manifest code declares an activity that handles  orientation|screenSize|screenLayout|keyboardHidden .....
         
` android:configChanges="orientation|screenSize|screenLayout|keyboardHidden"`

the  'onConfigurationChanged' its triggered on any that configuration change (orientation|screenSize|screenLayout|keyboardHidden), NOT ONLY  in orientation change

Always that 'onConfigurationChanged' is called the IF bellow will be TRUE
 if (newConfig.orientation == Configuration.ORIENTATION_LANDSCAPE || newConfig.orientation == Configuration.ORIENTATION_PORTRAIT) {
...
}

[https://github.com/admob-plus/admob-plus/blob/0345504c4b788fbddbc666622072123cd71ed475/packages/cordova/src/android/ads/Banner.java#L191](https://github.com/admob-plus/admob-plus/blob/0345504c4b788fbddbc666622072123cd71ed475/packages/cordova/src/android/ads/Banner.java#L191)

You need save the previous orientation and if this changed then call 'reloadBannerView();'

**Comment by victorvhpg** [comment]
@ratson thanks
