### ISSUE TITLE
java.lang.NoSuchMethodException from banner.load on Android ("Fail to create ad")

### ISSUE THREAD

**Issue by chriswardo** [admob-plus/admob-plus#330]
**Describe the bug**
`banner.load` results in a NoSuchMethodException with message "Fail to create ad".

Output from adb logcat (device connected via USB):
```
java.lang.NoSuchMethodException: a.a.k.d.<init> [class a.a.j]
	at java.lang.Class.getConstructor0(Class.java:2332)
	at java.lang.Class.getDeclaredConstructor(Class.java:2170)
	at a.a.j.d(SourceFile:2)
	at admob.plugin.AdMob.r(SourceFile:1)
	at a.a.f.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**To Reproduce**
```
try {
  await admob.start();
  banner = new admob.BannerAd({ adUnitId: 'ca-app-pub-3940256099942544/6300978111' });
  await banner.load();
  await banner.show();
} catch (e) {
  console.log(e); // Outputs "Fail to create ad"
}
```

**Expected behavior**
Banner ad should display but it doesn't.

**Environment**

```

  AdMob Plus Environment Info:
    System:
      OS: macOS Big Sur 11.1
      CPU: (8) x64 Apple M1
      Memory: 140.63 MB / 8.00 GB
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.1 - /usr/local/bin/node
      npm: 7.6.2 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    Utilities:
      Clang: 12.0.0 - /usr/bin/clang
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 29, 30
        Build Tools: 30.0.2, 30.0.3, 31.0.0
        System Images: android-30 | Google APIs Intel x86 Atom, android-S | Google APIs ARM 64 v8a, android-S | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7199119
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    Languages:
      Java: 1.8.0_271 - /usr/bin/javac
    npmPackages:
      admob-plus-cordova: ^1.10.0 => 1.10.0 
      cordova-android: ^9.1.0 => 9.1.0 
      cordova-browser: ^6.0.0 => 6.0.0 
      cordova-ios: ^6.2.0 => 6.2.0 
      cordova-launch-review: ^4.0.0 => 4.0.1 
      cordova-plugin-androidx-adapter: ^1.1.3 => 1.1.3 
      cordova-plugin-deeplinks: ^1.1.1 => 1.1.1 
      cordova-plugin-device: ^2.0.3 => 2.0.3 
      cordova-plugin-insomnia: ^4.3.0 => 4.3.0 
      cordova-plugin-localization-strings: 3.2.1 => 3.2.1 
      cordova-plugin-proguard: ^2.2.0 => 2.2.0 
      cordova-plugin-splashscreen: ^6.0.0 => 6.0.0 
      cordova-plugin-statusbar: ^2.4.3 => 2.4.3 
      cordova-plugin-theme-detection: ^1.2.1 => 1.3.0 
      cordova-plugin-whitelist: ^1.3.4 => 1.3.4 
    npmGlobalPackages:
      cordova: 10.0.0
    Cordova:
      Version: 10.0.0
      Plugins:
        cordova-plugin-whitelist: ^1.3.4
        cordova-plugin-statusbar: ^2.4.3
        cordova-plugin-theme-detection: ^1.2.1
        cordova-plugin-device: ^2.0.3
        cordova-plugin-splashscreen: ^6.0.0
        cordova-plugin-insomnia: ^4.3.0
        cordova-plugin-proguard: ^2.2.0
        cordova-launch-review: ^4.0.0
        cordova-plugin-deeplinks: ^1.1.1
        cordova-plugin-localization-strings: 3.2.1
        admob-plus-cordova: ^1.10.0
        cordova-plugin-androidx-adapter: ^1.1.3
    Ionic:
      Version: -
    AndroidManifest.xml:
      <meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" ... />: looks ok

```

**Additional context**

Output from `npx admob-plus doctor`:
```
✔ googleads.g.doubleclick.net
❯ CocoaPods
  ✖ Google-Mobile-Ads-SDK: 8.4.0 != 8.3.0
✔ package.json
  ✔ cordova.plugins.admob-plus-cordova.APP_ID_ANDROID
  ✔ cordova.plugins.admob-plus-cordova.APP_ID_IOS
❯ Cordova Android dependencies
  ✖ com.google.android.gms:play-services-ads: 20.1.0
✔ config.xml
  ✔ platform[name="ios"]/preference[name="SwiftVersion"]: 5.3
  ✔ platform[name="ios"]/preference[name="deployment-target"]: 12.0
  ↓ ANDROID_PLAY_SERVICES_CORE_VERSION [SKIPPED]
  ↓ TRANSLATION_PATH [SKIPPED]
  ✔ APP_ID_ANDROID
  ✔ APP_ID_IOS
  ✔ PLAY_SERVICES_VERSION
  ↓ USAGE [SKIPPED]
  ↓ DISABLESDKCRASHREPORTING [SKIPPED]
✔ platforms/ios/Game.xcodeproj
  ✔ SWIFT_VERSION: 5.3
✔ plugins/admob-plus-cordova/package.json
  ✔ admob-plus-cordova: 1.10.0
```

**Comment by ratson** [comment]
@chriswardo I could run your code without issue, would you create a test repo for me to check?

**Comment by chriswardo** [comment]
After an immensely frustrating week of trying everything and being completely baffled, I've finally fixed it!

If using Proguard, you need to add the following to your proguard file for this plugin to work:
```
-keep public class admob.plugin.ads.** {
 public *;
}
```

I'm amazed that no one else has come across this issue, but I recommend adding it to the README for others. Without that proguard rule, the code is removed and it results in the exception I posted before.

**Comment by MaximPerry** [comment]
@chriswardo Hey, I may sound like a total noob here (and I am)... but where is that proguard file you're referring too? Should it be at the root of the Cordova project along side config.xml, package.json, etc.? I'm not seeing that...
