### ISSUE TITLE
App crashes when opening

### ISSUE THREAD

**Issue by kabouter** [admob-plus/admob-plus#379]
Could you help me, please?

This is an old project. I was using Admob free first.

**Describe the bug**
I added Admob Plus to my cordova app, but my app crashes instantly. Directly after opening the app. 
 
I deleted all the admob javascript and it is still crashing. I build the app again after I removed the admob plugin and my app doesn't crash anymore.

**To Reproduce**
1. cordova plugin add admob-plus-cordova --save --variable APP_ID_ANDROID=ca-a
pp-pub-3940256099942544 --variable APP_ID_IOS=ca-app-pub-3940256099942544
2. cordova build
3. install APK 
4. Crash when opening the app

**Expected behavior**
I want to see the start screen of my app.

**Environment**

```
npx: installed 264 in 10.933s

  AdMob Plus Environment Info:
    System:
      OS: Windows 10 10.0.19043
      CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
      Memory: 8.84 GB / 15.94 GB
    Binaries:
      Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7351085
    npmPackages:
      cordova-android: ^9.1.0 => 9.1.0
      cordova-android-play-services-gradle-release: ^4.0.0 => 4.0.0
      cordova-plugin-androidx: ^3.0.0 => 3.0.0
      cordova-plugin-androidx-adapter: ^1.1.3 => 1.1.3
      cordova-plugin-whitelist: ^1.3.4 => 1.3.4
    Cordova:
      Version: 10.0.0
      Plugins:
        cordova-plugin-whitelist: ^1.3.4
        cordova-plugin-androidx: ^3.0.0
        cordova-android-play-services-gradle-release: ^4.0.0
        cordova-plugin-androidx-adapter: ^1.1.3
    Ionic:
      Version: -
    AndroidManifest.xml:
      <meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" ... />: looks ok

```

**Additional context**
I'm building for android.
```
npx: installed 264 in 11.237s
✔ googleads.g.doubleclick.net
✔ package.json
  ✔ cordova.plugins.admob-plus-cordova.APP_ID_ANDROID
  ✔ cordova.plugins.admob-plus-cordova.APP_ID_IOS
↓ Cordova Android dependencies [SKIPPED]
❯ config.xml
  ✖ platform[name="ios"]/preference[name="SwiftVersion"]: Error: platform[name="ios"]/preference[name="SwiftVersion"]…
  ✖ platform[name="ios"]/preference[name="deployment-target"]: Error: platform[name="ios"]/preference[name="deploymen…
↓ platforms/ios/*.xcodeproj [SKIPPED]
✔ plugins/admob-plus-cordova/package.json
  ✔ admob-plus-cordova: 1.17.0
```
**cordova plugin list**
```
admob-plus-cordova 0.0.0 "admob-plus-cordova"
cordova-android-play-services-gradle-release 4.0.0 "cordova-android-play-services-gradle-release"
cordova-plugin-androidx-adapter 1.1.3 "cordova-plugin-androidx-adapter"
cordova-plugin-androidx 3.0.0 "cordova-plugin-androidx"
cordova-plugin-whitelist 1.3.4 "Whitelist"

```
**config.xml**
```
<?xml version='1.0' encoding='utf-8'?>
<widget id="net.blibli.blabla" version="1.0.2" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>blabla</name>
    <description>
        A sample Apache Cordova application that responds to the deviceready event.
    </description>
    <author email="dev@cordova.apache.org" href="http://cordova.io">
        Apache Cordova Team
    </author>
    <content src="index.html" />
    <plugin name="cordova-plugin-whitelist" spec="1" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <platform name="android">
        <allow-intent href="market:*" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
    </platform>
	<preference name="android-minSdkVersion" value="25" />
<preference name="android-targetSdkVersion" value="25" />
<preference name="compileSdkVersion" value="30" />
    <platform name="android">
        <preference name="AndroidXEnabled" value="true" />
    </platform>
</widget>
```
**package.json**
```
{
  "name": "net.blibli.blalbla",
  "displayName": "blabla",
  "version": "1.0.1",
  "description": "A sample Apache Cordova application that responds to the deviceready event.",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [
    "ecosystem:cordova"
  ],
  "author": "Apache Cordova Team",
  "license": "Apache-2.0",
  "dependencies": {},
  "devDependencies": {
    "cordova-android": "^9.1.0",
    "cordova-android-play-services-gradle-release": "^4.0.0",
    "cordova-plugin-androidx": "^3.0.0",
    "cordova-plugin-androidx-adapter": "^1.1.3",
    "cordova-plugin-whitelist": "^1.3.4"
  },
  "cordova": {
    "plugins": {
      "cordova-plugin-whitelist": {},
      "cordova-plugin-androidx": {},
      "cordova-android-play-services-gradle-release": {
        "PLAY-SERVICES-ADS": "19.8.0",
        "PLAY-SERVICES-ADS-IDENTIFIER": "17.0.0",
        "PLAY-SERVICES-ADS-LITE": "18.0.0",
        "PLAY-SERVICES-AFS-NATIVE": "17.0.0",
        "PLAY-SERVICES-ANALYTICS": "17.0.0",
        "PLAY-SERVICES-ANALYTICS-IMPL": "17.0.0",
        "PLAY-SERVICES-APPINVITE": "18.0.0",
        "PLAY-SERVICES-AUDIENCE": "17.0.0",
        "PLAY-SERVICES-AUTH": "17.0.0",
        "PLAY-SERVICES-AUTH-API-PHONE": "17.0.0",
        "PLAY-SERVICES-AWARENESS": "17.0.0",
        "PLAY-SERVICES-BASE": "17.0.0",
        "PLAY-SERVICES-BASEMENT": "17.0.0",
        "PLAY-SERVICES-CAST": "17.0.0",
        "PLAY-SERVICES-CAST-FRAMEWORK": "17.0.0",
        "PLAY-SERVICES-CLEARCUT": "17.0.0",
        "PLAY-SERVICES-CRONET": "17.0.0",
        "PLAY-SERVICES-DRIVE": "17.0.0",
        "PLAY-SERVICES-FIDO": "18.0.0",
        "PLAY-SERVICES-FITNESS": "17.0.0",
        "PLAY-SERVICES-FLAGS": "17.0.0",
        "PLAY-SERVICES-GAMES": "18.0.0",
        "PLAY-SERVICES-GASS": "18.0.0",
        "PLAY-SERVICES-GCM": "17.0.0",
        "PLAY-SERVICES-IDENTITY": "17.0.0",
        "PLAY-SERVICES-IID": "17.0.0",
        "PLAY-SERVICES-INSTANTAPPS": "17.0.0",
        "PLAY-SERVICES-LOCATION": "17.0.0",
        "PLAY-SERVICES-MAPS": "17.0.0",
        "PLAY-SERVICES-MEASUREMENT": "17.0.0",
        "PLAY-SERVICES-MEASUREMENT-API": "17.0.0",
        "PLAY-SERVICES-MEASUREMENT-IMPL": "17.0.0",
        "PLAY-SERVICES-MEASUREMENT-SDK": "17.0.0",
        "PLAY-SERVICES-MEASUREMENT-SDK-API": "17.0.0",
        "PLAY-SERVICES-NEARBY": "17.0.0",
        "PLAY-SERVICES-OSS-LICENSES": "17.0.0",
        "PLAY-SERVICES-PANORAMA": "17.0.0",
        "PLAY-SERVICES-PHENOTYPE": "17.0.0",
        "PLAY-SERVICES-PLACES": "17.0.0",
        "PLAY-SERVICES-PLACES-PLACEREPORT": "17.0.0",
        "PLAY-SERVICES-PLUS": "17.0.0",
        "PLAY-SERVICES-SAFETYNET": "17.0.0",
        "PLAY-SERVICES-STATS": "17.0.0",
        "PLAY-SERVICES-TAGMANAGER": "17.0.0",
        "PLAY-SERVICES-TAGMANAGER-API": "17.0.0",
        "PLAY-SERVICES-TAGMANAGER-V4-IMPL": "17.0.0",
        "PLAY-SERVICES-TASKS": "17.0.0",
        "PLAY-SERVICES-VISION": "18.0.0",
        "PLAY-SERVICES-VISION-COMMON": "18.0.0",
        "PLAY-SERVICES-VISION-IMAGE-LABEL": "18.0.0",
        "PLAY-SERVICES-WALLET": "17.0.0",
        "PLAY-SERVICES-WEARABLE": "17.0.0"
      },
      "cordova-plugin-androidx-adapter": {},
      "admob-plus-cordova": {
        "APP_ID_ANDROID": "ca-app-pub-3940256099942544",
        "APP_ID_IOS": "ca-app-pub-3940256099942544",
        "PLAY_SERVICES_VERSION": "20.1.0"
      }
    },
    "platforms": [
      "android"
    ]
  }
}
```

**Comment by kabouter** [comment]
I think this is the output. Invalid application ID and java.lang.RuntimeException: Unable to get provider com.google.android.g
ms.ads.MobileAdsInitProvider: java.lang.IllegalStateException: are main issues? I'm not good at this.
```
06-14 15:42:05.217  2594  2658 I ActivityManager: Start proc 3627:net.blibli.blabla/u0a245 for pre-top-activity {net
.blibli.blabla/net.blibli.blabla.MainActivity}
06-14 15:42:05.223  3627  3627 I blibl.blabl: Late-enabling -Xcheck:jni
06-14 15:42:05.245  3627  3627 I blibl.blabl: Unquickening 12 vdex files!
06-14 15:42:05.258  2033  2040 I adbd    : jdwp connection from 3627
06-14 15:42:05.344  3627  3627 D ApplicationLoaders: Returning zygote-cached class loader: /system/framework/android.tes
t.base.jar
06-14 15:42:05.350  3627  3627 I blibl.blabl: The ClassLoaderContext is a special shared library.
06-14 15:42:05.495  3627  3627 D NetworkSecurityConfig: No Network Security Config specified, using platform default
06-14 15:42:05.496  3627  3627 D NetworkSecurityConfig: No Network Security Config specified, using platform default
06-14 15:42:05.498  3627  3627 D AndroidRuntime: Shutting down VM
06-14 15:42:05.499  3627  3627 E AndroidRuntime: FATAL EXCEPTION: main
06-14 15:42:05.499  3627  3627 E AndroidRuntime: Process: net.blibli.blabla, PID: 3627
06-14 15:42:05.499  3627  3627 E AndroidRuntime: java.lang.RuntimeException: Unable to get provider com.google.android.g
ms.ads.MobileAdsInitProvider: java.lang.IllegalStateException:
06-14 15:42:05.499  3627  3627 E AndroidRuntime:
06-14 15:42:05.499  3627  3627 E AndroidRuntime: ***********************************************************************
*******
06-14 15:42:05.499  3627  3627 E AndroidRuntime: * Invalid application ID. Follow instructions here:
      *
06-14 15:42:05.499  3627  3627 E AndroidRuntime: * https://googlemobileadssdk.page.link/admob-android-update-manifest
      *
06-14 15:42:05.499  3627  3627 E AndroidRuntime: * to find your app ID.
      *
06-14 15:42:05.499  3627  3627 E AndroidRuntime: ***********************************************************************
*******
06-14 15:42:05.499  3627  3627 E AndroidRuntime:
06-14 15:42:05.499  3627  3627 E AndroidRuntime:
06-14 15:42:05.499  3627  3627 E AndroidRuntime:        at android.app.ActivityThread.installProvider(ActivityThread.jav
a:7247)
06-14 15:42:05.499  3627  3627 E AndroidRuntime:        at android.app.ActivityThread.installContentProviders(ActivityTh
read.java:6783)
06-14 15:42:05.499  3627  3627 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThre
ad.java:6700)
06-14 15:42:05.499  3627  3627 E AndroidRuntime:        at android.app.ActivityThread.access$1300(ActivityThread.java:23
7)
06-14 15:42:05.499  3627  3627 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.jav
a:1913)
06-14 15:42:05.499  3627  3627 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
06-14 15:42:05.499  3627  3627 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:223)
06-14 15:42:05.499  3627  3627 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7660)
06-14 15:42:05.499  3627  3627 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-14 15:42:05.499  3627  3627 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(R
untimeInit.java:592)
06-14 15:42:05.499  3627  3627 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
06-14 15:42:05.499  3627  3627 E AndroidRuntime: Caused by: java.lang.IllegalStateException:
06-14 15:42:05.499  3627  3627 E AndroidRuntime:
06-14 15:42:05.499  3627  3627 E AndroidRuntime: ***********************************************************************
*******
06-14 15:42:05.499  3627  3627 E AndroidRuntime: * Invalid application ID. Follow instructions here:
      *
06-14 15:42:05.499  3627  3627 E AndroidRuntime: * https://googlemobileadssdk.page.link/admob-android-update-manifest
      *
06-14 15:42:05.499  3627  3627 E AndroidRuntime: * to find your app ID.
      *
06-14 15:42:05.499  3627  3627 E AndroidRuntime: ***********************************************************************
*******
06-14 15:42:05.499  3627  3627 E AndroidRuntime:
06-14 15:42:05.499  3627  3627 E AndroidRuntime:
06-14 15:42:05.499  3627  3627 E AndroidRuntime:        at com.google.android.gms.internal.ads.zzzx.attachInfo(com.googl
e.android.gms:play-services-ads-lite@@19.8.0:24)
06-14 15:42:05.499  3627  3627 E AndroidRuntime:        at com.google.android.gms.ads.MobileAdsInitProvider.attachInfo(c
om.google.android.gms:play-services-ads-lite@@19.8.0:3)
06-14 15:42:05.499  3627  3627 E AndroidRuntime:        at android.app.ActivityThread.installProvider(ActivityThread.jav
a:7242)
06-14 15:42:05.499  3627  3627 E AndroidRuntime:        ... 10 more
06-14 15:42:05.503  2594  8512 W ActivityTaskManager:   Force finishing activity net.blibli.blabla/.MainActivity
06-14 15:42:05.511  2594  7877 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
06-14 15:42:05.553  2594  2657 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent
.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
06-14 15:42:05.555  3627  3627 I Process : Sending signal. PID: 3627 SIG: 9
06-14 15:42:05.558  2594  2657 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent
.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$Persist
entTrustedReceiver
06-14 15:42:05.618  2594  5605 I ActivityManager: Process net.blibli.blabla (pid 3627) has died: prcp TOP
06-14 15:42:05.619  2594  2661 I libprocessgroup: Successfully killed process cgroup uid 10245 pid 3627 in 0ms
06-14 15:42:05.621  2024  2024 I Zygote  : Process 3627 exited due to signal 9 (Killed)
06-14 15:42:05.911  2594  2610 I system_server: NativeAlloc concurrent copying GC freed 241471(11MB) AllocSpace objects,
 123(7240KB) LOS objects, 47% free, 26MB/50MB, paused 84us total 147.413ms
06-14 15:42:05.956  2594  2612 W System  : A resource failed to call release.
06-14 15:42:06.008  2594  2646 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{50c4538
 u0 net.blibli.blabla/.MainActivity t-1 f}}
```

**Comment by kabouter** [comment]
Thank you for your support!

I created my app in admob and added a proper app ID.

My app is launching.
