### ISSUE TITLE
Native ads ERROR - crash app - CORDOVA

### ISSUE THREAD

**Issue by victorvhpg** [admob-plus/admob-plus#388]
this error occurs on Android version 5, 6  and 7 

at: admob.plus.cordova.ads.Native.show

error:

 `Fatal Exception: java.lang.NullPointerException
       at java.util.Objects.requireNonNull(Objects.java:98)
       at admob.plus.cordova.ads.Native.show(Native.java:113)
       at admob.plus.cordova.AdMob.lambda$executeAdShow_$3(AdMob.java:179)
       at admob.plus.cordova.-$$Lambda$AdMob$CkYp781_aIl5JGVakeRIswxuSKQ.run(lambda)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5624)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)`

<img width="1416" alt="Screen Shot 2021-06-18 at 09 11 18" src="https://user-images.githubusercontent.com/333451/122559269-7faf0800-d015-11eb-850b-b22673d78ba1.png">

**Comment by vietnux** [comment]
your error maybe your config fail

ex:
  await ad.show({
    x: 0,
    y: 50,
    width: window.screen.width, ======> my app error a here
    height: 300,
  })

**Comment by ratson** [comment]
@victorvhpg would you if the latest version fixes this?

**Comment by creakosta** [comment]
@ratson error still present and increased in new version
![3kucEGxtUuA](https://user-images.githubusercontent.com/15105267/124011231-74ca7f00-d9e8-11eb-9d40-b8d48382311b.jpg)

**Comment by creakosta** [comment]
Hi @ratson 
Can you fix it? i am ready to pay for it 100$
