### ISSUE TITLE
Error receiving null NativeAd - CORDOVA

### ISSUE THREAD

**Issue by HeberthFeres** [admob-plus/admob-plus#389]
Sometimes NativeAD is null.

`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.android.gms.ads.nativead.NativeAd.getHeadline()' on a null object reference
       at admob.plus.cordova.nativead.AdViewProvider.createView(AdViewProvider.java:46)
       at admob.plus.cordova.ads.Native.show(Native.java:108)
       at admob.plus.cordova.AdMob.lambda$executeAdShow_$3(AdMob.java:179)
       at admob.plus.cordova.-$$Lambda$AdMob$CkYp781_aIl5JGVakeRIswxuSKQ.run(:2)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:8057)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)`

**Comment by EYALIN** [comment]
@HeberthFeres can you update the plugin and the native plugin to the latest version and try again?
