### ISSUE TITLE
Lates version of library is broken for iOS & Android (Error: No ad config)

### ISSUE THREAD

**Issue by ShivamJoker** [admob-plus/admob-plus#445]
**Describe the bug**
While trying the latest release of library I am getting error on both android and iOS

```sh
Error: No ad config.
    at promiseMethodWrapper (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.sql_playground&modulesOnly=false&runModule=true:2521:45)
    at anonymous (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.sql_playground&modulesOnly=false&runModule=true:214685:50)
    at call (native)
    at step (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.sql_playground&modulesOnly=false&runModule=true:214585:25)
    at anonymous (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.sql_playground&modulesOnly=false&runModule=true:214515:20)
    at fulfilled (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.sql_playground&modulesOnly=false&runModule=true:214469:30)
    at tryCallOne (/tmp/hermes/staging/hermes/cmake/intlDebug/x86/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/tmp/hermes/staging/hermes/cmake/intlDebug/x86/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.sql_playground&modulesOnly=false&runModule=true:28390:26)
    at _callTimer (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.sql_playground&modulesOnly=false&runModule=true:28286:17)
    at _callImmediatesPass (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.sql_playground&modulesOnly=false&runModule=true:28325:17)
    at callImmediates (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.sql_playground&modulesOnly=false&runModule=true:28535:33)
    at __callImmediates (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.sql_playground&modulesOnly=false&runModule=true:2979:35)
    at anonymous (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.sql_playground&modulesOnly=false&runModule=true:2757:34)
    at __guard (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.sql_playground&modulesOnly=false&runModule=true:2962:15)
    at flushedQueue (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.sql_playground&modulesOnly=false&runModule=true:2756:21)
    at invokeCallbackAndReturnFlushedQueue (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.sql_playground&modulesOnly=false&runModule=true:2749:33)
```

**Environment**

```

  AdMob Plus Environment Info:
    System:
      OS: macOS Big Sur 11.6
      CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 35.75 MB / 16.00 GB
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.8.0 - ~/.nvm/versions/node/v16.8.0/bin/node
      Yarn: 1.22.15 - ~/.yarn/bin/yarn
      npm: 7.21.0 - ~/.nvm/versions/node/v16.8.0/bin/npm
      Watchman: 2021.09.06.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    Utilities:
      Clang: 12.0.1 - /usr/local/opt/llvm/bin/clang
    SDKs:
      iOS SDK:
        Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 31.0.0
        System Images: android-28 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7678000
      Xcode: 13.0/13A233 - /usr/bin/xcodebuild
    Languages:
      Java: 1.8.0_302 - /usr/local/opt/openjdk@8/bin/javac
    Cordova:
      Version: -
    Ionic:
      Version: -
    AndroidManifest.xml:
      Version: -
```

**Comment by ShivamJoker** [comment]
@ratson you need help in testing ?
I don't have much idea about admob and native stuffs so if you need any specific logs let me know.

**Comment by ShivamJoker** [comment]
I am also getting this

Module AdMobPlusRN requires main queue setup since it overrides `init` but doesn't implement `requiresMainQueueSetup`. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.

**Comment by keev-studio** [comment]
Hi, any progress on this?

**Comment by ShivamJoker** [comment]
@keev-studio I've switched to react native admob, it has awesome hooks.
