### ISSUE TITLE
[ANDROID-CAPACITOR] java.lang.IllegalStateException: The specified child already has a parent. You must call removeView()

### ISSUE THREAD

**Issue by jmateu88** [admob-plus/admob-plus#457]
**To Reproduce**
1. Open app
2. Display ad
3. Back button android until app is closed but in memory
4. Open app
5. App crashes and throws the below exception

**Describe the bug**
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
        at android.view.ViewGroup.addViewInner(ViewGroup.java:5235)
        at android.view.ViewGroup.addView(ViewGroup.java:5064)
        at android.view.ViewGroup.addView(ViewGroup.java:5004)
        at android.view.ViewGroup.addView(ViewGroup.java:4976)
        at admob.plus.capacitor.ads.Banner.addBannerView(Banner.java:141)
        at admob.plus.capacitor.ads.Banner.show(Banner.java:93)
        at admob.plus.capacitor.AdMobPlusPlugin.lambda$adShow$4(AdMobPlusPlugin.java:137)
        at admob.plus.capacitor.-$$Lambda$AdMobPlusPlugin$avt3_Ai0StBKuiBSOBx7XMk52zo.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Expected behavior**
App opens with no issues

**Environment**

```
  AdMob Plus Environment Info:
    System:
      OS: Windows 10 10.0.22000
      CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor             
      Memory: 21.04 GB / 31.91 GB
    Binaries:
      Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7784292
    npmPackages:
      typescript: ^3.9.10 => 3.9.10 
    Cordova:
      Version: -
    Ionic:
      Version: 6.16.3
    AndroidManifest.xml:
      Version: -

```

**Comment by ben-kn-app** [comment]
+1 Experiencing the same problem for a production app and the problem is reproducible with above description. Will try to search for a workaround until this problem is fixed. 

PS: This was not a problem with the cordova variant of this plugin.
