### ISSUE TITLE
Native Ad does not load in Russia. Generating a Null exception and crash the app

### ISSUE THREAD

**Issue by juanico18** [admob-plus/admob-plus#538]
Steps to reproduce:
1 Implement native Ads.
2 Display native ads on a device in Russia. Also is valid to use a service as BrowserStack
3 On call to show after checking if the native is loaded. The next error appears

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.android.gms.ads.nativead.NativeAd.getHeadline()' on a null object reference
       at admob.plus.cordova.nativead.AdViewProvider.createView(AdViewProvider.java:46)
       at admob.plus.cordova.ads.Native.show(Native.java:108)
       at admob.plus.cordova.AdMob.lambda$executeAdShow$3(AdMob.java:175)

Based on comments on the code, it should never be null. But I think that because country restrictions are null

**Comment by juanico18** [comment]
We have prevent the problem by capturing the event on load fail. In that case we do not try to show the ad.
