### ISSUE TITLE
Cannot find [...] in scope

### ISSUE THREAD

**Issue by skol-pro** [admob-plus/admob-plus#552]
**Describe the bug**
Getting lots of "Cannot find [...] in scope" errors in `AMBInterstitial.swift` and `AMBRewarded.swift` files.

**To Reproduce**
1. Follow every installation guides
2. Try to build using Xcode

**Expected behavior**
Not getting those errors.

**Screenshots**
![Screenshot 2022-12-21 at 16 15 35](https://user-images.githubusercontent.com/10620177/208939628-65333467-6419-434a-bb32-2d45e9fe23da.png)

**Environment**
Running `npx admob-plus info --clipboard` unfortunately gives the following output (and error): 
```
admob-plus info

Get relevant version info about OS, toolchain and libraries

Options:
  --version    Show version number                                     [boolean]
  --cwd                                                  [string] [default: "."]
  --help       Show help                                               [boolean]
  --clipboard  Copy the environment report output to the clipboard     [boolean]

TypeError: fse.readJson is not a function
    at Function.read (file:///Users/vincent/.npm/_npx/25aeecf2c60cb292/node_modules/pkg-proxy/lib/index.js:37:31)
    at Function.find (file:///Users/vincent/.npm/_npx/25aeecf2c60cb292/node_modules/pkg-proxy/lib/index.js:34:25)
    at async Function.createProxy (file:///Users/vincent/.npm/_npx/25aeecf2c60cb292/node_modules/pkg-proxy/lib/index.js:19:21)
    at async Object.handler (file:///Users/vincent/.npm/_npx/25aeecf2c60cb292/node_modules/admob-plus/lib/cmds/info.js:40:23)
```

**Comment by netlob** [comment]
Same for Cordova here. Any updates?

**Comment by EYALIN** [comment]
@netlob @skol-pro did you try the latest plugin version?
