### ISSUE TITLE
App crashes immediately after opening

### ISSUE THREAD

**Issue by MichielJ87** [admob-plus/admob-plus#573]
**Describe the bug**
My app crashes immediately after launching the app.
I excluded all plugins except the admob-plus plugin and my app still crashes, so I assume the crash is related to the plugin.

I build my app in the cloud using Ionic Appflow (because I am a novice and I don't have the skill to build locally).
I only build for Android.

In Google Play Console I have the following crash error:
dalvik.system.BaseDexClassLoader.findClass
java.lang.ClassNotFoundException

error details:
type: java.lang.RuntimeException
Exception java.lang.RuntimeException:
  at android.app.LoadedApk.makeApplicationInner (LoadedApk.java:1573)
  at android.app.LoadedApk.makeApplicationInner (LoadedApk.java:1502)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:7553)
  at android.app.ActivityThread.-$$Nest$mhandleBindApplication
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2400)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:226)
  at android.os.Looper.loop (Looper.java:313)
  at android.app.ActivityThread.main (ActivityThread.java:8757)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:571)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1067)
Caused by java.lang.ClassNotFoundException:
  at dalvik.system.BaseDexClassLoader.findClass (BaseDexClassLoader.java:259)
  at java.lang.ClassLoader.loadClass (ClassLoader.java:379)
  at java.lang.ClassLoader.loadClass (ClassLoader.java:312)
  at android.app.AppComponentFactory.instantiateApplication (AppComponentFactory.java:76)
  at androidx.core.app.CoreComponentFactory.instantiateApplication (CoreComponentFactory.java:52)
  at android.app.Instrumentation.newApplication (Instrumentation.java:1232)
  at android.app.LoadedApk.makeApplicationInner (LoadedApk.java:1565)

**To Reproduce**
1. Include the plugin in config.xml (see below)
2. Build app in Ionic appflow (see details belows)
3. Download apk, install apk
4. Open app

**Expected behavior**
App does not crash when launching.

**Environment**
I build my app in the cloud using Ionic appflow.

This is the environment info from the build log:
+---------------------+----------+
| Build Summary |
+---------------------+----------+
| Job ID | 8569156 |
| Node.js version | v18.12.1 |
| Cordova CLI version | 11.0.0 |
| npm version | 8.19.3 |
| yarn version | 1.22.19 |
+---------------------+----------+

I run my build using an additional environment setting (which I found online, without this setting my build gives an error):
key: OVERRIDE_JAVA_VERSION
value: 11

**Additional context**
Below my config.xml configuration related to the plugin.
My results is the same (crash on app open) when I include or exclude all my other plugins, which is why I don't mention those in the description below.

My widget config contains:
xmlns:android="http://schemas.android.com/apk/res/android"

Inside of my config.xml:

<plugin name="admob-plus-cordova" spec="1.28.0">
    <variable name="APP_ID_ANDROID" value="ca-app-pub-7462917676626966~2253912345" />
</plugin>

<platform name="android">
    <edit-config file="AndroidManifest.xml" mode="merge" target="/manifest/application" xmlns:android="http://schemas.android.com/apk/res/android">
        <meta-data 
        android:name="com.google.android.gms.ads.APPLICATION_ID"
        android:value="ca-app-pub-7462917676626966~2253912345" /> --> I changed some numbers here since this is my actual id (not test-id)
    </edit-config>
</platform>

<preference name="AndroidXEnabled" value="true" />

<preference name="android-minSdkVersion" value="28" /> --> This was first 22. I changed to 28, but same result (crash on startup)
<preference name="android-targetSdkVersion" value="31" />
<preference name="android-compileSdkVersion" value="31" />

My package.json does not contain anything relevant to this plugin
(note I am building in the cloud using ionic appflow, so I think this is ok, however feel free offcourse to correct me)

Some info (not sure if relevant):
I successfully used before cordova-admob-pro with my admob id. I am switching to this plugin because I fail to build cordova-admob-pro with a play services version >= 20
I tried myself to investigate similar problems. I looked at this thread https://github.com/admob-plus/admob-plus/issues/379 but the clue there was the wrong id was used. ChatGPT and Bing Chat also failed to provide me a solution :)

Many thanks in advance for anybody willing to help me!
Michiel

**Comment by MichielJ87** [comment]
Somehow my config.xml info got removed.
Here it is again

<plugin name="admob-plus-cordova" spec="1.28.0">
    <variable name="APP_ID_ANDROID" value="ca-app-pub-7462917676626966~2253912345" />
</plugin>

<platform name="android">
    <edit-config file="AndroidManifest.xml" mode="merge" target="/manifest/application" xmlns:android="http://schemas.android.com/apk/res/android">
        <meta-data 
        android:name="com.google.android.gms.ads.APPLICATION_ID"
        android:value="ca-app-pub-7462917676626966~2253912345" />
    </edit-config>
</platform>

<preference name="AndroidXEnabled" value="true" />
<plugin name="cordova-plugin-androidx-adapter" source="npm" />

<preference name="android-minSdkVersion" value="28" />
<preference name="android-targetSdkVersion" value="31" />
<preference name="android-compileSdkVersion" value="31" />

**Comment by EYALIN** [comment]
@MichielJ87 This plugin is not maintained anymore, please move to the maintained one.
you can follow this post: https://github.com/admob-plus/admob-plus/issues/574

**Comment by MichielJ87** [comment]
Thanks for your feedback! I really appreciate a new community maintained plugin.

Unfortunately for now when i build with the plugin you mentioned and launch my app it still gives the same error (see 1st post).

Not sure if this is something which can be fixed?

Kind regards,
Michiel

**Comment by EYALIN** [comment]
@MichielJ87 can you please verify it's related to this plugin by removing it and upload again?
i had this issue before and it's happen on phones without play services (from what I remember) 

is it failing on a specific phone? all phones?
if it's one crash from a lot of devices, so it's related to play service which not installed

**Comment by MichielJ87** [comment]
> @MichielJ87 can you please verify it's related to this plugin by removing it and upload again? i had this issue before and it's happen on phones without play services (from what I remember)
> 
> is it failing on a specific phone? all phones? if it's one crash from a lot of devices, so it's related to play service which not installed

Hi there,
It is failing on multiple phones (with different versions of android installed).
When I build my app without the admob community plugin my app is not crashing (on the same phones).
If you need any more info feel free to let me know.
Kind regards,
Michiel

**Comment by MichielJ87** [comment]
> @MichielJ87 can you please install those 2 plugins: ![image](https://user-images.githubusercontent.com/12213426/231524248-de3fe638-8a96-45f0-8cb2-1918c7be61df.png)
> 
> they should fix the multiDex issue

Hi, I build with those plugins but unfortunately still have the same error when opening my app.
I do appreciate your help, thanks!
Michiel

**Comment by gmalhotra1979** [comment]
Having the same issue here on Pixel6.  Cordova version is 11.1.0  Java version is 11.0.19 No other plugin other than community-admob-plus-cordova 
The app builds but won't launch on my pixel6. Launches fine when I get rid of the plugin :/

**Comment by anuskaoo** [comment]
I have the same problem. How can I fix it?

**Comment by EYALIN** [comment]
@anuskaoo @gmalhotra1979 @MichielJ87  it's happened to me sometimes when it's not installed correctly. (and then i just remove and add the plugin again)
can you please get the exception from logcat?

**Comment by anuskaoo** [comment]
@gmalhotra1979 @MichielJ87  I removed the platform and I put it again and It work. But now the ads don't show at the first time. I don't know why. If I put a button to call the function, it works fine (although I have to press it several times). The function doesn't run on the deviceready and I don't know why. Thanks for helping

**Comment by Mr-Anonymous** [comment]
I have the exact issue. Here are more info on my issue:

1. After I added `<preference name="android-targetSdkVersion" value="31" />` I started having this issue. 
2. When I open the app from my Samsung Galaxy S23, the app crashes immedietly. When I remove this plugin `cordova rm admob-plus-cordova` the app works. 
3. I tried adding `cordova-plugin-androidx-adapter` and `cordova-plugin-androidx` and it doesn't help.
4. I tried adding `android-targetSdkVersion` and `android-compileSdkVersion` to `33` and I still have the same problem.
5. I am unable to find any error logs since it crashes straight away. But from the Google Play console I see this:
```
android.app.PendingIntent.checkFlags
java.lang.IllegalArgumentException
```

Can you help me resolve this please?

Here are my ionic info and plugins list:

```
$ cordova plugins list
admob-plus-cordova 1.28.0 "admob-plus-cordova"
cordova-plugin-androidx-adapter 1.1.3 "cordova-plugin-androidx-adapter"
cordova-plugin-androidx 3.0.0 "cordova-plugin-androidx"
cordova-plugin-consent 2.4.0 "@admob-plus/cordova-consent"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-inappbrowser 5.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 5.0.0 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 6.0.2 "Splashscreen"
cordova-plugin-statusbar 3.0.0 "StatusBar"
cordova-plugin-x-socialsharing 6.0.4 "SocialSharing"
es6-promise-plugin 4.2.2 "Promise"
```
```
$ ionic info

Ionic:

   Ionic CLI                     : 7.1.1 (/Users/me/.nvm/versions/node/v16.13.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.7.4
   @angular-devkit/build-angular : 13.0.4
   @angular-devkit/schematics    : 13.0.4
   @angular/cli                  : 13.0.4
   @ionic/angular-toolkit        : 5.0.3

Cordova:

   Cordova CLI       : 11.0.0
   Cordova Platforms : android 10.1.2, ios 6.3.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 8 other plugins)

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.2

System:

   Android SDK Tools : 26.1.1 (/Users/neel/Library/Android/sdk)
   ios-sim           : 8.0.2
   NodeJS            : v16.13.0 (/Users/neel/.nvm/versions/node/v16.13.0/bin/node)
   npm               : 8.1.0
   OS                : macOS Monterey
   Xcode             : Xcode 14.2 Build version 14C18


```

Java version is `11.0.19` and gradle version is `6.9.4`.

**Comment by ratson** [comment]
@Mr-Anonymous Is there anything showing in ` adb logcat`?
There is not enough information for me to know what crash the app.

**Comment by Mr-Anonymous** [comment]
@ratson Thanks for getting back to me. I was able to grab the error in Logcat. It says this:

```
2023-05-30 23:28:24.124 7741-7741/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.app.mobile, PID: 7741
    java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException: 
    
    ******************************************************************************
    * Invalid application ID. Follow instructions here:                          *
    * https://googlemobileadssdk.page.link/admob-android-update-manifest         *
    * to find your app ID.                                                       *
    ******************************************************************************
    
    
        at android.app.ActivityThread.installProvider(ActivityThread.java:8328)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:7828)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7577)
        at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2400)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8757)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
     Caused by: java.lang.IllegalStateException: 
    
    ******************************************************************************
    * Invalid application ID. Follow instructions here:                          *
    * https://googlemobileadssdk.page.link/admob-android-update-manifest         *
    * to find your app ID.                                                       *
    ******************************************************************************
    
    
        at com.google.android.gms.internal.ads.zzbjr.attachInfo(com.google.android.gms:play-services-ads-lite@@20.6.0:22)
        at com.google.android.gms.ads.MobileAdsInitProvider.attachInfo(com.google.android.gms:play-services-ads-lite@@20.6.0:1)
        at android.app.ActivityThread.installProvider(ActivityThread.java:8323)
        	... 11 more

```

**Comment by Mr-Anonymous** [comment]
Sorry, the error makes sense. The `com.google.android.gms.ads.APPLICATION_ID` was missing. Might have gotten missed when the plugin was updated. I removed the plugin and re-added it in the format `cordova plugin add admob-plus-cordova --save --variable APP_ID_ANDROID=ca-app-pub-xxx~xxx --variable APP_ID_IOS=ca-app-pub-xxx~xxx` and it worked fine after that. Sorry about that. Didn't mean to hijack this thread and I am not sure if the OP had the same issue, but my one got resolved once I reinstalled the plugin with the App Id.

**Comment by anuskaoo** [comment]
Hello again. The ads were not loading because I was printing them before the index.html was loaded and they were "behind". Now it works well. Thanks for your help

**Comment by ratson** [comment]
@ MichielJ87 Do you able to solve the issues?

@gmalhotra1979 Which version of `admob-plus-cordova` did you try?
Feel free to mention the plugin you are using here, love to learn from it.

**Comment by gmalhotra1979** [comment]
@ratson 
(1) ended up going with https://npm.io/package/cordova-plugin-ads - I am using the donottrack one
(2) i am not sure which version I had used for admob-plus 
Essentially whichever version that gets installed when you do cordova plugin add admob-plus-cordova sorry if that's not helpful...I have removed it from my project and am unable to tell you which version it was!

**Comment by ratson** [comment]
@gmalhotra1979 
Make sure you aware this line,
https://github.com/cozycodegh/cordova-plugin-ads/blob/main/www/ads.js#L32

**Comment by EYALIN** [comment]
@pedrumgolriz it seems that you are on the old native plugin, upgrade to the latest. (v0.3.0)

**Comment by pedrumgolriz** [comment]
hmm ok, I removed the old plugin and did ionic cordova plugin add admob-plus-cordova-native@0.3.0 --save, however I get a few java errors now and wont run:

It seems that the 1.0.0-alpha.4 is the latest according to npm though

```
[cordova] /Users/pedrumgolriz/Documents/Dev/myappname/platforms/android/app/src/main/java/admob/plus/cordova/nativead/Plugin.java:9: error: cannot find symbol
[cordova] import admob.plus.cordova.AdMob;
[cordova]                          ^
[cordova]   symbol:   class AdMob
[cordova]   location: package admob.plus.cordova
[cordova] /Users/pedrumgolriz/Documents/Dev/myappname/platforms/android/app/src/main/java/admob/plus/cordova/nativead/Plugin.java:10: error: package admob.plus.cordova.ads does not exist
[cordova] import admob.plus.cordova.ads.Native;
[cordova]                              ^
[cordova] /Users/pedrumgolriz/Documents/Dev/myappname/platforms/android/app/src/main/java/admob/plus/cordova/nativead/AdViewProvider.java:17: error: package admob.plus.cordova.ads does not exist
[cordova] import admob.plus.cordova.ads.Native;
[cordova]                              ^
[cordova] /Users/pedrumgolriz/Documents/Dev/myappname/platforms/android/app/src/main/java/admob/plus/cordova/nativead/AdViewProvider.java:19: error: package Native does not exist
[cordova] public class AdViewProvider implements Native.ViewProvider {
[cordova]                                              ^
[cordova] /Users/pedrumgolriz/Documents/Dev/myappname/platforms/android/app/src/main/java/admob/plus/cordova/nativead/Plugin.java:20: error: package Native does not exist
[cordova]         AdMob.registerNativeAdViewProviders(new HashMap<String, Native.ViewProvider>() {{
[cordova]                                                                       ^
[cordova] /Users/pedrumgolriz/Documents/Dev/myappname/platforms/android/app/src/main/java/admob/plus/cordova/nativead/Plugin.java:21: error: cannot find symbol
[cordova]             put(AdMob.NATIVE_VIEW_DEFAULT, new AdViewProvider(cordova));
[cordova]                 ^
[cordova]   symbol: variable AdMob
[cordova] /Users/pedrumgolriz/Documents/Dev/myappname/platforms/android/app/src/main/java/admob/plus/cordova/nativead/Plugin.java:20: error: cannot find symbol
[cordova]         AdMob.registerNativeAdViewProviders(new HashMap<String, Native.ViewProvider>() {{
[cordova]         ^
[cordova]   symbol:   variable AdMob
[cordova]   location: class Plugin
[cordova] /Users/pedrumgolriz/Documents/Dev/myappname/platforms/android/app/src/main/java/admob/plus/cordova/nativead/AdViewProvider.java:27: error: method does not override or implement a method from a supertype
[cordova]     @Override
[cordova]     ^
[cordova] 8 errors
```

**Comment by EYALIN** [comment]
@pedrumgolriz it seems that you don't have the native package.
can you install the latest admob-plus and latest native (0.3) ?
it will work

**Comment by pedrumgolriz** [comment]
Awesome thank you @ratson @EYALIN, what finally worked were the following packages:
"admob-plus-cordova": "^1.28.0",
    "admob-plus-cordova-native": "^0.3.0",
    "admob-plus-cordova-webview-ad": "^0.1.0",
    
    I think what was tripping me up was the alpha packages, as I generally install with latest tags
