### ISSUE TITLE
Cannot read properties of undefined

### ISSUE THREAD

**Issue by melihozlem** [admob-plus/admob-plus#590]
Followed all the instructions seeing below error on version 1.7.0

[INFO:CONSOLE(40328)] "ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'start')
                                                                                                    TypeError: Cannot read properties of undefined (reading 'start')
                                                                                                        at push../node_modules/@admob-plus/ionic/ngx/index.js.AdMob.start (https://localhost/vendor.js:320:24)

**Comment by melihozlem** [comment]
@ratson is there more information I need to provide?

**Comment by melihozlem** [comment]
I tried to install using 
ionic cordova plugin add admob-plus-cordova
npm install @admob-plus/ionic

when I try to build android release, I see this error:

```
cordova-android-play-services-gradle-release: overriding com.google.android.gms:play-services-ads:20.6.0 in build.gradle with com.google.android.gms:play-services-ads:18.0.0
Error: ENOENT: no such file or directory, scandir './platforms/android/cordova-android-play-services-gradle-release'
    at Object.readdirSync (node:fs:1452:3)
    at processPackages (C:\projects\fbaScanner\plugins\cordova-android-play-services-gradle-release\scripts\apply-changes.js:164:103)
    at _fulfilled (C:\projects\fbaScanner\node_modules\q\q.js:854:54)
    at C:\projects\fbaScanner\node_modules\q\q.js:883:30
    at Promise.promise.promiseDispatch (C:\projects\fbaScanner\node_modules\q\q.js:816:13)
    at C:\projects\fbaScanner\node_modules\q\q.js:570:49
    at runSingle (C:\projects\fbaScanner\node_modules\q\q.js:137:13)
    at flush (C:\projects\fbaScanner\node_modules\q\q.js:125:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
````

**Comment by ratson** [comment]
@melihozlem Would you refer to [this example](https://github.com/admob-plus/admob-plus/blob/master/examples/ionic-angular/src/app/home/home.page.ts) about how to use `admob-plus-cordova` without using a wrapper. 
The latest version no longer need the `@admob-plus/ionic` wrapper, which is not documented yet.

**Comment by melihozlem** [comment]
I see following errors when I do `ionic cordova build android`

```
cordova-android-play-services-gradle-release: overriding com.google.android.gms:play-services-ads:20.6.0 in build.gradle with com.google.android.gms:play-services-ads:18.0.0
The "<splash>" tags were detected and are no longer supported. Please migrate to the "preference" tag "AndroidWindowSplashScreenAnimatedIcon".
cordova-android-play-services-gradle-release: overriding com.google.android.gms:play-services-ads:20.6.0 in build.gradle with com.google.android.gms:play-services-ads:18.0.0
Preparing Firebase on Android


> Task :app:compileDebugJavaWithJavac FAILED
\platforms\android\app\src\main\java\admob\plus\core\Helper.java:16: error: cannot find symbol
import com.google.android.gms.ads.RequestConfiguration;
                                 ^
  symbol:   class RequestConfiguration
  location: package com.google.android.gms.ads
\platforms\android\app\src\main\java\admob\plus\cordova\ads\Native.java:11: error: cannot find symbol
import com.google.android.gms.ads.LoadAdError;
```

**Comment by melihozlem** [comment]
@ratson I noticed every time I try to do `ionic cordova build android` in the Application.manifest file this line gets added
```
        <meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="ca-app-pub-xxx~yyy" />

**Comment by melihozlem** [comment]
> 

When I remove `cordova-android-play-services-gradle-release` I get errors
```
 error: cannot find symbol
    private com.google.android.gms.ads.InterstitialAd interstitialAd = null;
```

**Comment by ratson** [comment]
@melihozlem What is the output `npx admob-plus@latest doctor`?

**Comment by melihozlem** [comment]
> npx admob-plus@latest

npx admob-plus@latest doctor
Need to install the following packages:
  admob-plus@2.0.0-alpha.9
Ok to proceed? (y)

**Comment by melihozlem** [comment]
@ratson I installed the package above, and this is the output
```
✔ googleads.g.doubleclick.net
✔ package.json
⚠ Cordova Android dependencies
  ✖ com.google.android.gms:play-services-ads: 20.6.0
⚠ config.xml
  ✖ platform[name="ios"]/preference[name="SwiftVersion"]: Error: platform[name="ios"]/preference[name="SwiftVersion"]:
  missing / invalid
  ✖ platform[name="ios"]/preference[name="deployment-target"]: Error:
  platform[name="ios"]/preference[name="deployment-target"]: missing / invalid
  ↓ ANDROID_SUPPORT_ANNOTATIONS_VERSION
↓ platforms/ios/*.xcodeproj
⚠ plugins/admob-plus-cordova/package.json
  ✖ admob-plus-cordova: 1.28.0 < 2.0.0-alpha.10
    › Update to latest version: 2.0.0-alpha.10
```

**Comment by melihozlem** [comment]
@ratson i've tried updating. Now I see:
```
npx admob-plus@latest doctor
✔ googleads.g.doubleclick.net
✔ package.json
⚠ Cordova Android dependencies
  ✖ com.google.android.gms:play-services-ads: 20.6.0
⚠ config.xml
  ✖ platform[name="ios"]/preference[name="SwiftVersion"]: Error: platform[name="ios"]/preference[name="SwiftVersion"]:
  missing / invalid
  ✖ platform[name="ios"]/preference[name="deployment-target"]: Error:
  platform[name="ios"]/preference[name="deployment-target"]: missing / invalid
  ↓ ANDROID_SUPPORT_ANNOTATIONS_VERSION
↓ platforms/ios/*.xcodeproj
↓ plugins/admob-plus-cordova/package.json
```

and when I attempt ionic build I get
```
ERROR in ../node_modules/@admob-plus/ionic/ngx/index.d.ts:2:13 - error TS1005: '=' expected.

2 import type { AdMob as IAdMob, BannerAd as IBannerAd, BannerAdOptions, InterstitialAd as IInterstitialAd, NativeAdOptions, RewardedAd as IRewardedAd, RewardedAdOptions, RewardedInterstitialAd as IRewardedInterstitialAd, NativeAd as INativeAd, RewardedInterstitialAdOptions } from 'admob-plus-cordova';
              ~
../node_modules/@admob-plus/ionic/ngx/index.d.ts:2:281 - error TS1005: ';' expected.

2 import type { AdMob as IAdMob, BannerAd as IBannerAd, BannerAdOptions, InterstitialAd as IInterstitialAd, NativeAdOptions, RewardedAd as IRewardedAd, RewardedAdOptions, RewardedInterstitialAd as IRewardedInterstitialAd, NativeAd as INativeAd, RewardedInterstitialAdOptions } from 'admob-plus-cordova';
```
my package.json dependencies
```
  "dependencies": {
    "@admob-plus/ionic": "^2.0.0-alpha.11",
    "@angular/common": "^8.2.0",
    "@angular/core": "^8.2.0",
    "@angular/forms": "^8.2.0",
    "@angular/platform-browser": "^8.2.0",
    "@angular/platform-browser-dynamic": "^8.2.0",
    "@angular/router": "^8.2.0",
    "@ionic-native/barcode-scanner": "^5.5.0",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/http": "^5.5.0",
    "@ionic-native/in-app-browser": "^5.5.0",
    "@ionic-native/paypal": "^5.5.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^5.9.4",
    "@ionic/cordova-builders": "^9.0.0",
    "@ionic/storage": "^2.2.0",
    "card.io.cordova.mobilesdk": "2.1.0",
    "com.paypal.cordova.mobilesdk": "3.5.0",
    "cordova-android": "^11.0.0",
    "cordova-plugin-advanced-http": "2.0.9",
    "cordova-plugin-file": "6.0.1",
    "cordova-plugin-inappbrowser": "^3.2.0",
    "core-js": "^2.5.4",
    "dom-parser": "^0.1.6",
    "phonegap-plugin-barcodescanner": "8.0.1",
    "rxjs": "~6.6.0",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },
  ```

**Comment by EYALIN** [comment]
@melihozlem one of your plugins using very old play services SDK.
try to track which plugin 20.6.0, and when removing it i think it will be fixed

**Comment by melihozlem** [comment]
@EYALIN I was forcing the version of play services shoudl it be? I was forcing it in the build.gradle file via
```
configurations.all {
  resolutionStrategy {
    force "com.google.android.gms:play-services-ads:20.6.0"
 }
}
```

**Comment by EYALIN** [comment]
@melihozlem it should be 22.1.0
but who is forcing? you? or a plugin?

**Comment by melihozlem** [comment]
@EYALIN I added this to build.gradle otherwise I see errors:
```
configurations.all {
  resolutionStrategy {
    force "com.google.android.gms:play-services-ads:22.1.0"
 }
}
```

I now get:
```
 npx admob-plus@latest doctor
✔ googleads.g.doubleclick.net
✔ package.json
✔ Cordova Android dependencies
⚠ config.xml
  ✖ platform[name="ios"]/preference[name="SwiftVersion"]: Error: platform[name="ios"]/preference[name="SwiftVersion"]:
  missing / invalid
  ✖ platform[name="ios"]/preference[name="deployment-target"]: Error:
  platform[name="ios"]/preference[name="deployment-target"]: missing / invalid
  ↓ ANDROID_SUPPORT_ANNOTATIONS_VERSION
↓ platforms/ios/*.xcodeproj
↓ plugins/admob-plus-cordova/package.json
````
and still see error:

```
ERROR in ../node_modules/@admob-plus/ionic/ngx/index.d.ts:2:13 - error TS1005: '=' expected.

2 import type { AdMob as IAdMob, BannerAd as IBannerAd, BannerAdOptions, InterstitialAd as IInterstitialAd, NativeAdOptions, RewardedAd as IRewardedAd, RewardedAdOptions, RewardedInterstitialAd as IRewardedInterstitialAd, NativeAd as INativeAd, RewardedInterstitialAdOptions } from 'admob-plus-cordova';
```

This is not coming from play services

**Comment by EYALIN** [comment]
@melihozlem I'm also an Ionic user, but I use the Cordova plugin and not Ionic which is more active.
you are using a very old Ionic and typescript version and maybe it's not fit. 
can you remove the ionic plugin "@admob-plus/ionic" and install the Cordova one (Alpha 12 - latest )

the cordova plugin should do the work

**Comment by melihozlem** [comment]
@EYALIN  I have ran ` npm uninstall @admob-plus/ionic` to remove `@admob-plus/ionic` . What is the command to install the cordova version of the plugin you mention?

I use ionic 5 which provides free plugins which ionic has switched to enterprise where you have to pay to install the plugin. Therefore, I have to use ionic 5.

**Comment by EYALIN** [comment]
@melihozlem ionic is still free, even in version 7.
anyway, to install the Cordova plugin follow this guide:
https://admob-plus.github.io/docs/cordova/installation
(use the second example via Cordova CLI)

**Comment by melihozlem** [comment]
@EYALIN  I did 
```
 ionic cordova plugin add admob-plus-cordova --save --variable APP_ID_ANDROID=ca-app-pub --variable APP_ID_IOS=ca-app-pub
 ```
when I try to build I get the error;
````
 Cannot use namespace 'AdMob' as a type.

 constructor(private admob: AdMob,
```
How would I import this? I currently have:

```
import { AdMob } from "@admob-plus/ionic/ngx";
```
Do I have to update that?

In ionic I need the plugins and only version 5 provides them according to https://ionicframework.com/docs/v5/native/barcode-scanner

**Comment by EYALIN** [comment]
@melihozlem remove the usings of admob ionic.
you need to reimport them

**Comment by melihozlem** [comment]
@EYALIN what would I import?

**Comment by EYALIN** [comment]
@melihozlem import { AdMob } from "@admob-plus/ionic/ngx";

**Comment by EYALIN** [comment]
@melihozlem please remove all ionic admob implementation or any admob that you have and follow the cordova guide .

when writing this:
`import { AdMob } from "@admob-plus/ionic/ngx";`

it means that you are still using admob ionic. remove any "@admob-plus/ionic/".

**Comment by melihozlem** [comment]
@EYALIN I removed the reference at the top of the file. then added this inside the constructor
```
    const banner = new admob.BannerAd({
      adUnitId: _ADMOBUNITID,
      });
      banner.show();
```
I get an error
```
error TS2304: Cannot find name 'admob'.

81     const banner = new admob.BannerAd({
                          ~~~~~
````

If I remove the import at the top how is it going to find where admob library is located?

**Comment by EYALIN** [comment]
@melihozlem you need to import it from Cordova.

@melihozlem you have all you need in the guides for this plugin.

@ratson I think you can close this ticket

**Comment by melihozlem** [comment]
@EYALIN I cannot find what to import or an example for ioinic here: https://admob-plus.github.io/docs/cordova/ads/banner . Where are you referring to?

**Comment by EYALIN** [comment]
@melihozlem you need to import from Cordova and not from Ionic, such as this:
`import { AdSizeType, BannerAd, BannerAdOptions } from 'admob-plus-cordova'; 
`

also, please work with the guides, and IDE such as webStorm, it will help you.

the questions here are not issues.

@ratson you can close this ticket.

**Comment by melihozlem** [comment]
@EYALIN I find this error with those changes
```
> Task :app:compileReleaseJavaWithJavac
\platforms\android\app\src\main\java\admob\plus\cordova\AdMob.java:66: error: cannot find symbol
                        put("version", MobileAds.getVersionString());
                                                ^
  symbol:   method getVersionString()
  location: class MobileAds
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

```

**Comment by melihozlem** [comment]
@EYALIN no banner is showing up. In the logs I see
```
Execute banner_show
```
my code is 
```
    const banner = new admob.BannerAd({
      adUnitId: _ADMOBUNITID,
      });
      banner.show();
```
Is there some way to debug what's going on?

**Comment by EYALIN** [comment]
@melihozlem please follow the guide. you need to load it first

**Comment by melihozlem** [comment]
I don't see the banner and I also see a message `Ready action should only be called once.` 

The code inside the constructor of home.page.ts looks like this:
```
import { AdSizeType, BannerAd, BannerAdOptions } from 'admob-plus-cordova';  
...
constructor(    private platform: Platform,
    public router: Router
){

    this.platform.ready().then(async () => {

      const banner = new admob.BannerAd({
        adUnitId: _ADMOBUNITID2,
      });

     await banner.load()
     await banner.show()
    }); 

}
````

I did remove `this.platform.ready()` from other places in the code, so I think `Ready action should only be called once.` is coming from Admob.

Do I need to do anything in app.module.ts? I removed the reference to Admob since this is not getting imported directly. Since the direct import differs from the docs, I can't really follow what's missing. A simple example would help.

**Comment by EYALIN** [comment]
@melihozlem it seems that _ADMOBUNITID2 not defined.
please replace it with "ca-app-pub-3940256099942544/6300978111" so you will see it working.
it is the test ad

**Comment by melihozlem** [comment]
@EYALIN still no banner shows. I see logs:
```
023-07-16 20:44:40.743 14803-14803 PluginManager              D  startupPlugins: put - AdMob
2023-07-16 20:44:41.119 14803-15018 AdMobPlus                  I  Initialize plugin
2023-07-16 20:44:41.120 14803-15018 PluginManager            D  getPlugin - put: AdMob
2023-07-16 20:44:41.120 14803-15018 AdMobPlus                D  Execute ready
2023-07-16 20:44:41.126 14803-15018 AdMobPlus                 D  Execute ready
2023-07-16 20:44:41.126 14803-15018 AdMobPlus                 E  Ready action should only be called once.
```
Is there something else I could print or check?

**Comment by melihozlem** [comment]
@EYALIN I noticed there is also error
```
[INFO:CONSOLE(39963)] "ERROR Error: Uncaught (in promise): TypeError: banner.load is not a function
                                                                                                    TypeError: banner.load is not a function
                                                                                                        at HomePage.<anonymous> (https://localhost/home-home-module.js:155:53)
                                                                                                        at step (https://localhost/polyfills.js:3227:23)
                                                                                                        at Object.next (https://localhost/polyfills.js:3208:53)
                                                                                                        at https://localhost/polyfills.js:3201:71
                                                                                                        at new ZoneAwarePromise (https://localhost/polyfills.js:4286:29)
                                                                                                        at Module.__awaiter (https://localhost/polyfills.js:3197:12)
                                                                                                        at https://localhost/home-home-module.js:147:104
                                                                                                        at push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (https://localhost/polyfills.js:3746:26)
                                                                                                        at Object.onInvoke (https://localhost/vendor.js:62217:33)
                                                                                                        at push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (https://localhost/polyfills.js:3745:52)", source: https://localhost/vendor.js (39963)
```

**Comment by EYALIN** [comment]
@melihozlem change your code to : 
```
this.platform.ready().then(async () => {

      const banner = await new admob.BannerAd({
        adUnitId: _ADMOBUNITID2,
      });

     await banner.load()
     await banner.show()
    }); 
```

you forgot to add "await"

**Comment by melihozlem** [comment]
@EYALIN I made the change and still see the same error
