### ISSUE TITLE
@ratson  **This problem is not yet solved**, see the attached screenshot for the latest app version

### ISSUE THREAD

**Issue by merbin2012** [admob-plus/admob-plus#592]
@ratson  **This problem is not yet solved**, see the attached screenshot for the latest app version

![screenshot-nimbusweb me-2023 06 20-09_12_47](https://github.com/admob-plus/admob-plus/assets/3687184/81bdf57f-47a3-4d0a-8931-228c11fee308)

![screenshot-nimbusweb me-2023 06 20-09_15_21](https://github.com/admob-plus/admob-plus/assets/3687184/bd9b38b2-d7ed-4078-b5ed-deeddb9fbad3)

**Crash logs from playstore**
`Exception java.lang.RuntimeException:
  at android.app.ActivityThread.performDestroyActivity (ActivityThread.java:5265)
  at android.app.ActivityThread.handleDestroyActivity (ActivityThread.java:5296)
  at android.app.servertransaction.DestroyActivityItem.execute (DestroyActivityItem.java:44)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:176)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:97)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2130)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:223)
  at android.app.ActivityThread.main (ActivityThread.java:8001)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:635)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:947)
Caused by java.util.ConcurrentModificationException:
  at java.util.LinkedHashMap$LinkedHashIterator.nextNode (LinkedHashMap.java:757)
  at java.util.LinkedHashMap$LinkedEntryIterator.next (LinkedHashMap.java:790)
  at java.util.LinkedHashMap$LinkedEntryIterator.next (LinkedHashMap.java:788)
  at admob.plus.cordova.AdMob.onDestroy (AdMob.kt:219)
  at org.apache.cordova.PluginManager.onDestroy (PluginManager.java:339)
  at org.apache.cordova.CordovaWebViewImpl.handleDestroy (CordovaWebViewImpl.java:531)
  at org.apache.cordova.CordovaActivity.onDestroy (CordovaActivity.java:327)
  at android.app.Activity.performDestroy (Activity.java:8362)
  at android.app.Instrumentation.callActivityOnDestroy (Instrumentation.java:1344)
  at android.app.ActivityThread.performDestroyActivity (ActivityThread.java:5250)`

_Originally posted by @merbin2012 in https://github.com/admob-plus/admob-plus/issues/588#issuecomment-1598066859_

**Comment by ratson** [comment]
@merbin2012 Are you using the NativeAd?

**Comment by merbin2012** [comment]
@ratson No I am not using it. Only using Banner, Interstitial, AppOpen ads.

**Comment by ratson** [comment]
@merbin2012 The latest version is switched to use a thread-safe Map, does that fix the issue?

**Comment by merbin2012** [comment]
Is it fixed? I do not yet check. I thought that issue is fixed for the native ads only. Today I will update the app and let you know the crash report within two days.

**Comment by SiempreProgramadorNovato** [comment]
Just to appreciate the amazing @ratson work. 

Thanks for your help and hope my app could grow up quickly to star contribute as soon as possible to this awesome project, that help thousands developers.

**Comment by merbin2012** [comment]
@ratson Hi, thanks for taking the time and try to fix the issue. Sorry, this is not yet solved.


![screenshot-nimbusweb me-2023 06 25-19_27_48](https://github.com/admob-plus/admob-plus/assets/3687184/b668462b-686c-4851-97ec-81fde3088443)

**Comment by merbin2012** [comment]
@ratson Hi, can you please fix this

**Comment by ratson** [comment]
@merbin2012 Would you share the crash log to see which line causing it?

**Comment by merbin2012** [comment]
@ratson in my device it is working and I can't find when it is crash. 
This is what I got in play console

```
Exception java.lang.RuntimeException:
  at android.app.ActivityThread.performDestroyActivity (ActivityThread.java:4424)
  at android.app.ActivityThread.handleDestroyActivity (ActivityThread.java:4442)
  at android.app.ActivityThread.-wrap5
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1683)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6548)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:438)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:857)
Caused by java.util.ConcurrentModificationException:
  at java.util.LinkedHashMap$LinkedHashIterator.nextNode (LinkedHashMap.java:757)
  at java.util.LinkedHashMap$LinkedEntryIterator.next (LinkedHashMap.java:790)
  at java.util.LinkedHashMap$LinkedEntryIterator.next (LinkedHashMap.java:790)
  at admob.plus.cordova.AdMob.onDestroy (AdMob.kt:231)
  at org.apache.cordova.PluginManager.onDestroy (PluginManager.java:339)
  at org.apache.cordova.CordovaWebViewImpl.handleDestroy (CordovaWebViewImpl.java:531)
  at org.apache.cordova.CordovaActivity.onDestroy (CordovaActivity.java:327)
  at android.app.Activity.performDestroy (Activity.java:7232)
  at android.app.Instrumentation.callActivityOnDestroy (Instrumentation.java:1249)
  at android.app.ActivityThread.performDestroyActivity (ActivityThread.java:4411)
```

**Comment by ratson** [comment]
@merbin2012 See if `admob-plus-cordova@2.0.0-alpha.11` fix that.

**Comment by merbin2012** [comment]
@ratson Thank you, I'll check and let you know.

**Comment by merbin2012** [comment]
@ratson Sorry, not yet resolved. I will try to check and find the issue line number.

![screenshot-play google com-2023 06 30-09_09_08](https://github.com/admob-plus/admob-plus/assets/3687184/d2080555-f7a5-4ddc-9f6f-8d93036f68dc)

**Comment by merbin2012** [comment]
@ratson I found a new problem, might this be related to this issue

For testing when I call _interstitial.hide() and _appOpen.hide() the following crash occur
Note: In code, I am not called "**_interstitial.hide()** and **_appOpen.hide()**" anywhere.


<img src="https://github.com/admob-plus/admob-plus/assets/3687184/6710ccb2-f10f-4e75-8a8a-0162c8ccc8a7" width="150px" />

**Android studio log**
`2023-06-30 09:18:16.408 31154-16664 AudioTrack              aud.xx.cc                       D  [audioTrackData][fine] 15s(f:15020 m:1975 s:0 k:0) : pid 31154 uid 10713 sessionId 11401 sr 44100 ch 2 fmt 1
2023-06-30 09:18:18.384 31154-31154 AndroidRuntime          aud.xx.cc                       D  Shutting down VM
2023-06-30 09:18:18.388 31154-31154 AndroidRuntime          aud.xx.cc                       E  FATAL EXCEPTION: main
                                                                                                    Process: aud.xx.cc, PID: 31154
                                                                                                    kotlin.NotImplementedError: An operation is not implemented: Not yet implemented
                                                                                                    	at admob.plus.cordova.ads.AdBase.hide(AdBase.kt:70)
                                                                                                    	at admob.plus.cordova.AdMob.executeAdHide$lambda$12(AdMob.kt:159)
                                                                                                    	at admob.plus.cordova.AdMob.$r8$lambda$a-0Ac5jH-7DFmbbVdN4N6922PWU(Unknown Source:0)
                                                                                                    	at admob.plus.cordova.AdMob$$ExternalSyntheticLambda5.run(Unknown Source:2)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:210)
                                                                                                    	at android.os.Looper.loop(Looper.java:299)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8261)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
2023-06-30 09:18:18.386 31154-31154 aud.xx.cc          aud.xx.cc                       W  type=1400 audit(0.0:181691): avc: denied { search } for name="miuilog" dev="dm-44" ino=388988 scontext=u:r:untrusted_app:s0:c201,c258,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=aud.xx.cc
2023-06-30 09:18:18.386 31154-31154 aud.xx.cc          aud.xx.cc                       W  type=1400 audit(0.0:181692): avc: denied { search } for name="miuilog" dev="dm-44" ino=388988 scontext=u:r:untrusted_app:s0:c201,c258,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=aud.xx.cc
2023-06-30 09:18:18.386 31154-31154 aud.xx.cc          aud.xx.cc                       W  type=1400 audit(0.0:181693): avc: denied { search } for name="miuilog" dev="dm-44" ino=388988 scontext=u:r:untrusted_app:s0:c201,c258,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=aud.xx.cc
2023-06-30 09:18:18.390 31154-31154 aud.xx.cc          aud.xx.cc                       W  type=1400 audit(0.0:181694): avc: denied { search } for name="miuilog" dev="dm-44" ino=388988 scontext=u:r:untrusted_app:s0:c201,c258,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=aud.xx.cc
2023-06-30 09:18:18.390 31154-31154 aud.xx.cc          aud.xx.cc                       W  type=1400 audit(0.0:181695): avc: denied { search } for name="miuilog" dev="dm-44" ino=388988 scontext=u:r:untrusted_app:s0:c201,c258,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=aud.xx.cc
2023-06-30 09:18:18.396 31154-31154 OOMEventManagerFK       aud.xx.cc                       W  Failed to mkdir /data/miuilog/stability/memleak/heapdump/
2023-06-30 09:18:18.409 31154-31154 aud.xx.cc          aud.xx.cc                       W  Attempt to remove non-JNI local reference, dumping thread
2023-06-30 09:18:18.446 31154-31154 Process                 aud.xx.cc                       I  Process is going to kill itself!
                                                                                                    java.lang.Exception
                                                                                                    	at android.os.Process.killProcess(Process.java:1344)
                                                                                                    	at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:181)
                                                                                                    	at org.chromium.base.JavaExceptionReporter.uncaughtException(chromium-TrichromeWebViewGoogle6432.aab-stable-573513133:17)
                                                                                                    	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
                                                                                                    	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
                                                                                                    	at java.lang.Thread.dispatchUncaughtException(Thread.java:2306)
2023-06-30 09:18:18.446 31154-31154 Process                 aud.xx.cc                       I  Sending signal. PID: 31154 SIG: 9`

**Comment by EYALIN** [comment]
@ratson also in some of my apps I can't install due to the Kotlin version.
I have Cordova 11.
if i will upgrade to 12 it will work, but i can't do this upgrade for now (they have icon bug there)
is anyone familiar with a workaround?

**Comment by merbin2012** [comment]
@EYALIN May I know the icon bug details? I think Cordova-12 is stable

**Comment by EYALIN** [comment]
@merbin2012 here you have the bug https://github.com/apache/cordova-android/issues/1616

and it's on the roadmap for 12.0.1 https://github.com/apache/cordova-android/milestone/16

if you have a workaround for it it will help me a lot

**Comment by ratson** [comment]
@EYALIN What Kotlin version issue do you have?
You can change the Kotlin version with `GradlePluginKotlinVersion` in `config.xml`.

**Comment by EYALIN** [comment]
@ratson great. which version do i need? will try it now

**Comment by EYALIN** [comment]
@ratson seems working, thanks a lot!

**Comment by EYALIN** [comment]
@ratson where do you want me to send feedback on the new Alpha version?
for example, when using "admob.configure" without setting the volume, i will get an exception

**Comment by EYALIN** [comment]
@ratson I saw that you fixed the latest Alpha (.12).
I will start performing tests tomorrow.

**Comment by EYALIN** [comment]
> @ratson I found a new problem, might this be related to this issue
> 
> For testing when I call _interstitial.hide() and _appOpen.hide() the following crash occur Note: In code, I am not called "**_interstitial.hide()** and **_appOpen.hide()**" anywhere.
> 
> <img alt="" width="150px" src="https://user-images.githubusercontent.com/3687184/249995885-6710ccb2-f10f-4e75-8a8a-0162c8ccc8a7.jpg">
> **Android studio log** `2023-06-30 09:18:16.408 31154-16664 AudioTrack aud.xx.cc D [audioTrackData][fine] 15s(f:15020 m:1975 s:0 k:0) : pid 31154 uid 10713 sessionId 11401 sr 44100 ch 2 fmt 1 2023-06-30 09:18:18.384 31154-31154 AndroidRuntime aud.xx.cc D Shutting down VM 2023-06-30 09:18:18.388 31154-31154 AndroidRuntime aud.xx.cc E FATAL EXCEPTION: main Process: aud.xx.cc, PID: 31154 kotlin.NotImplementedError: An operation is not implemented: Not yet implemented at admob.plus.cordova.ads.AdBase.hide(AdBase.kt:70) at admob.plus.cordova.AdMob.executeAdHide$lambda$12(AdMob.kt:159) at admob.plus.cordova.AdMob.$r8$lambda$a-0Ac5jH-7DFmbbVdN4N6922PWU(Unknown Source:0) at admob.plus.cordova.AdMob$$ExternalSyntheticLambda5.run(Unknown Source:2) at android.os.Handler.handleCallback(Handler.java:942) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loopOnce(Looper.java:210) at android.os.Looper.loop(Looper.java:299) at android.app.ActivityThread.main(ActivityThread.java:8261) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954) 2023-06-30 09:18:18.386 31154-31154 aud.xx.cc aud.xx.cc W type=1400 audit(0.0:181691): avc: denied { search } for name="miuilog" dev="dm-44" ino=388988 scontext=u:r:untrusted_app:s0:c201,c258,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=aud.xx.cc 2023-06-30 09:18:18.386 31154-31154 aud.xx.cc aud.xx.cc W type=1400 audit(0.0:181692): avc: denied { search } for name="miuilog" dev="dm-44" ino=388988 scontext=u:r:untrusted_app:s0:c201,c258,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=aud.xx.cc 2023-06-30 09:18:18.386 31154-31154 aud.xx.cc aud.xx.cc W type=1400 audit(0.0:181693): avc: denied { search } for name="miuilog" dev="dm-44" ino=388988 scontext=u:r:untrusted_app:s0:c201,c258,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=aud.xx.cc 2023-06-30 09:18:18.390 31154-31154 aud.xx.cc aud.xx.cc W type=1400 audit(0.0:181694): avc: denied { search } for name="miuilog" dev="dm-44" ino=388988 scontext=u:r:untrusted_app:s0:c201,c258,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=aud.xx.cc 2023-06-30 09:18:18.390 31154-31154 aud.xx.cc aud.xx.cc W type=1400 audit(0.0:181695): avc: denied { search } for name="miuilog" dev="dm-44" ino=388988 scontext=u:r:untrusted_app:s0:c201,c258,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=aud.xx.cc 2023-06-30 09:18:18.396 31154-31154 OOMEventManagerFK aud.xx.cc W Failed to mkdir /data/miuilog/stability/memleak/heapdump/ 2023-06-30 09:18:18.409 31154-31154 aud.xx.cc aud.xx.cc W Attempt to remove non-JNI local reference, dumping thread 2023-06-30 09:18:18.446 31154-31154 Process aud.xx.cc I Process is going to kill itself! java.lang.Exception at android.os.Process.killProcess(Process.java:1344) at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:181) at org.chromium.base.JavaExceptionReporter.uncaughtException(chromium-TrichromeWebViewGoogle6432.aab-stable-573513133:17) at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073) at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068) at java.lang.Thread.dispatchUncaughtException(Thread.java:2306) 2023-06-30 09:18:18.446 31154-31154 Process aud.xx.cc I Sending signal. PID: 31154 SIG: 9`

@ratson is this solved on Alpha 12? i have the same issue

**Comment by EYALIN** [comment]
@ratson @merbin2012 The problem still occurs at Alpha 12.
can't reproduce it locally, I see it only in crashlytics. 
this is the exception "java.util.ConcurrentModificationException" and it happens here :
![image](https://github.com/admob-plus/admob-plus/assets/12213426/812ea900-00f3-496e-8956-5bc6cd6be299)
at row 208

from what I read in Google it means (not sure how to fix it) : 
"concurrentmodificationexception is an error in Java. The error occurs when the iterator is traversing a list, and a command is used to change an element's value during that traversal."

**Comment by EYALIN** [comment]
@ratson can you maybe add try-catch there, for now, so we will not have those exceptions?

**Comment by mjapps-games** [comment]
Hey @ratson and @EYALIN, I wanted to let you know that I've tested the 2.0.0-alpha.13 version by creating an APK and running it on a real device. Unfortunately, the ads are still not working. For creating apk using [https://www.npmjs.com/package/admob-plus-cordova](url)

**Comment by EYALIN** [comment]
@mjapps-games thanks for the info. do you still see the same exception on the destroy hook?

**Comment by merbin2012** [comment]
@ratson hi brother, any update?

**Comment by ratson** [comment]
@merbin2012 Would you try `2.0.0-alpha.13` and let me know the result?

**Comment by merbin2012** [comment]
@ratson okay, tomorrow I'll let you know the result. Thanks for the reply.

**Comment by EYALIN** [comment]
@merbin2012 any news?

**Comment by merbin2012** [comment]
@EYALIN Update to the play store and waiting for approval and crash logs.

**Comment by EYALIN** [comment]
@merbin2012 @ratson i saw this now :
  4645 W System.err: java.lang.ClassNotFoundException: admob.plus.cordova.AdMob
07-13 21:37:50.140  4502  4645 W System.err: 	at java.lang.Class.classForName(Native Method)
07-13 21:37:50.140  4502  4645 W System.err: 	at java.lang.Class.forName(Class.java:454)
07-13 21:37:50.140  4502  4645 W System.err: 	at java.lang.Class.forName(Class.java:379)
07-13 21:37:50.140  4502  4645 W System.err: 	at org.apache.cordova.PluginManager.instantiatePlugin(PluginManager.java:566)
07-13 21:37:50.140  4502  4645 W System.err: 	at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:185)
07-13 21:37:50.140  4502  4645 W System.err: 	at org.apache.cordova.PluginManager.exec(PluginManager.java:138)
07-13 21:37:50.140  4502  4645 W System.err: 	at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
07-13 21:37:50.140  4502  4645 W System.err: 	at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
07-13 21:37:50.140  4502  4645 W System.err: 	at android.os.MessageQueue.nativePollOnce(Native Method)
07-13 21:37:50.140  4502  4645 W System.err: 	at android.os.MessageQueue.next(MessageQueue.java:335)
07-13 21:37:50.140  4502  4645 W System.err: 	at android.os.Looper.loopOnce(Looper.java:161)
07-13 21:37:50.140  4502  4645 W System.err: 	at android.os.Looper.loop(Looper.java:288)
07-13 21:37:50.140  4502  4645 W System.err: 	at android.os.HandlerThread.run(HandlerThread.java:67)
07-13 21:37:50.141  4502  4645 W System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "admob.plus.cordova.AdMob" on path: DexPathList[[zip file "/data/app/~~KTfFIdL2OnWqt0twnXuCKA==/com.blabla.blabla-F-SUZF8bOUkH_bG052lRHg==/base.apk"],nativeLibraryDirectories=[/data/app/~~KTfFIdL2OnWqt0twnXuCKA==/com.blabla.blabla-F-SUZF8bOUkH_bG052lRHg==/lib/arm64, /data/app/~~KTfFIdL2OnWqt0twnXuCKA==/com.blabla.blabla-F-SUZF8bOUkH_bG052lRHg==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
07-13 21:37:50.141  4502  4645 W System.err: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
07-13 21:37:50.141  4502  4645 W System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
07-13 21:37:50.141  4502  4645 W System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
07-13 21:37:50.141  4502  4645 W System.err: 	... 13 more
07-13 21:37:50.141  4502  4645 I System.out: Error adding plugin admob.plus.cordova.AdMob.
07-13 21:37:50.141  4502  4645 W System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CordovaPlugin.privateInitialize(java.lang.String, org.apache.cordova.CordovaInterface, org.apache.cordova.CordovaWebView, org.apache.cordova.CordovaPreferences)' on a null object reference
07-13 21:37:50.141  4502  4645 W System.err: 	at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:187)
07-13 21:37:50.141  4502  4645 W System.err: 	at org.apache.cordova.PluginManager.exec(PluginManager.java:138)
07-13 21:37:50.141  4502  4645 W System.err: 	at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
07-13 21:37:50.141  4502  4645 W System.err: 	at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
07-13 21:37:50.141  4502  4645 W System.err: 	at android.os.MessageQueue.nativePollOnce(Native Method)
07-13 21:37:50.141  4502  4645 W System.err: 	at android.os.MessageQueue.next(MessageQueue.java:335)
07-13 21:37:50.141  4502  4645 W System.err: 	at android.os.Looper.loopOnce(Looper.java:161)
07-13 21:37:50.141  4502  4645 W System.err: 	at android.os.Looper.loop(Looper.java:288)
07-13 21:37:50.141  4502  4645 W System.err: 	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by merbin2012** [comment]
@ratson @EYALIN 
Thank you ratson, this issue is fixed. I'm not seen any crash logs related to this.
