### ISSUE TITLE
Crash Issue In Android

### ISSUE THREAD

**Issue by wliadmin** [admob-plus/admob-plus#77]
W have created a new ionic 3 app, and use this plugin to show admob banner ads.

We have upload android app on google play store but we found many crashes issue reported on dashboard as below

**Issue Report 1 :** 
Crash:1 java.lang.NullPointerException, admob.plugin.AdMob.emit
Samsung Galaxy S9 (starqltesq), Android 9
Report 1
java.lang.NullPointerException: 
at admob.plugin.AdMob.emit (AdMob.java:109)
at admob.plugin.AdMob.emit (AdMob.java:95)
at admob.plugin.ads.AdListener.onAdLoaded (AdListener.java:14)
at com.google.android.gms.internal.ads.zzww.onAdLoaded (Unknown Source:24)
at com.google.android.gms.internal.ads.zzza.onAdLoaded (Unknown Source:3)
at com.google.android.gms.internal.ads.zzvx.onAdLoaded (Unknown Source:10)
at com.google.android.gms.internal.ads.zzxb.dispatchTransaction (Unknown Source:11)
at com.google.android.gms.internal.ads.zzex.onTransact (Unknown Source:12)
at android.os.Binder.transact (Binder.java:675)
at mv.b (com.google.android.gms.dynamite_adsdynamite@15090083@15.0.90 (100408-231259764):14)
at com.google.android.gms.ads.internal.client.ac.c (com.google.android.gms.dynamite_adsdynamite@15090083@15.0.90 (100408-231259764):10)
at com.google.android.gms.ads.internal.a.c (com.google.android.gms.dynamite_adsdynamite@15090083@15.0.90 (100408-231259764):321)
at com.google.android.gms.ads.internal.a.q (com.google.android.gms.dynamite_adsdynamite@15090083@15.0.90 (100408-231259764):316)
at com.google.android.gms.ads.internal.h.q (com.google.android.gms.dynamite_adsdynamite@15090083@15.0.90 (100408-231259764):18)
at com.google.android.gms.ads.internal.x.q (com.google.android.gms.dynamite_adsdynamite@15090083@15.0.90 (100408-231259764):121)
at com.google.android.gms.ads.internal.a.b (com.google.android.gms.dynamite_adsdynamite@15090083@15.0.90 (100408-231259764):177)
at com.google.android.gms.ads.internal.c.b (com.google.android.gms.dynamite_adsdynamite@15090083@15.0.90 (100408-231259764):44)
at com.google.android.gms.ads.internal.renderer.a.a (com.google.android.gms.dynamite_adsdynamite@15090083@15.0.90 (100408-231259764):25)
at com.google.android.gms.ads.internal.renderer.a.a (com.google.android.gms.dynamite_adsdynamite@15090083@15.0.90 (100408-231259764):10)
at com.google.android.gms.ads.internal.webview.j.p (com.google.android.gms.dynamite_adsdynamite@15090083@15.0.90 (100408-231259764):110)
at com.google.android.gms.ads.internal.webview.j.onPageFinished (com.google.android.gms.dynamite_adsdynamite@15090083@15.0.90 (100408-231259764):83)
at xH.c (SourceFile:222)
at ayK.handleMessage (SourceFile:72)
at android.os.Handler.dispatchMessage (Handler.java:106)
at android.os.Looper.loop (Looper.java:214)
at android.app.ActivityThread.main (ActivityThread.java:6981)
at java.lang.reflect.Method.invoke (Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1445)

**Issue Report 2 :**
Crash: 2 java.lang.NullPointerException
Motorola Moto Z(3) (messi), Android 8.1, admob.plugin.AdMob.emit
Report 1 of 2
java.lang.NullPointerException: 
at admob.plugin.AdMob.emit (AdMob.java:109)
at admob.plugin.ads.AdListener.onAdFailedToLoad (AdListener.java:19)
at com.google.android.gms.internal.ads.zzww.onAdFailedToLoad (Unknown Source:12)
at com.google.android.gms.internal.ads.zzza.onAdFailedToLoad (Unknown Source:6)
at com.google.android.gms.internal.ads.zzvx.onAdFailedToLoad (Unknown Source:6)
at com.google.android.gms.internal.ads.zzxb.dispatchTransaction (Unknown Source:7)
at com.google.android.gms.internal.ads.zzex.onTransact (Unknown Source:12)
at android.os.Binder.transact (Binder.java:627)
at og.b (com.google.android.gms.dynamite_adsdynamite@15090051@15.0.90 (040408-231259764):14)
at com.google.android.gms.ads.internal.client.ac.a (com.google.android.gms.dynamite_adsdynamite@15090051@15.0.90 (040408-231259764):6)
at com.google.android.gms.ads.internal.a.a (com.google.android.gms.dynamite_adsdynamite@15090051@15.0.90 (040408-231259764):333)
at com.google.android.gms.ads.internal.a.a (com.google.android.gms.dynamite_adsdynamite@15090051@15.0.90 (040408-231259764):329)
at com.google.android.gms.ads.internal.a.b (com.google.android.gms.dynamite_adsdynamite@15090051@15.0.90 (040408-231259764):140)
at com.google.android.gms.ads.internal.c.b (com.google.android.gms.dynamite_adsdynamite@15090051@15.0.90 (040408-231259764):44)
at com.google.android.gms.ads.internal.j.run (com.google.android.gms.dynamite_adsdynamite@15090051@15.0.90 (040408-231259764):2)
at android.os.Handler.handleCallback (Handler.java:790)
at android.os.Handler.dispatchMessage (Handler.java:99)
at ze.a (com.google.android.gms.dynamite_adsdynamite@15090051@15.0.90 (040408-231259764):5)
at com.google.android.gms.ads.internal.util.e.a (com.google.android.gms.dynamite_adsdynamite@15090051@15.0.90 (040408-231259764):11)
at ze.dispatchMessage (com.google.android.gms.dynamite_adsdynamite@15090051@15.0.90 (040408-231259764):4)
at android.os.Looper.loop (Looper.java:164)
at android.app.ActivityThread.main (ActivityThread.java:6728)
at java.lang.reflect.Method.invoke (Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:438)
at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:814)

Please find below attached screenshot for the same.

![crash_issue](https://user-images.githubusercontent.com/9083810/52951284-6b0bc800-33a7-11e9-8efd-addac7ddbc09.png)

Could you please check for this issue and let us know for it's solutions?

**Comment by Pezhvak** [comment]
i've created a fresh new ionic (v4) app, and i've the same issue, just this plugin installed and it gets crashes immediately after opening.

```
<plugin name="cordova-admob-plus" spec="0.24.1">
        <variable name="APP_ID_ANDROID" value="rewardca-app-pub-XXXXXX/XXXXXX" />
        <variable name="PLAY_SERVICES_VERSION" value="17.1.2" />
    </plugin>
    <engine name="android" spec="~6.2.3" />
```

**Comment by andrey3diq** [comment]
The same thing happens for my ionic 3 app:

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CallbackContext.sendPluginResult(org.apache.cordova.PluginResult)' on a null object reference
       at admob.plugin.AdMob.emit(AdMob.java:109)
       at admob.plugin.AdMob.emit(AdMob.java:95)
       at admob.plugin.ads.AdListener.onAdLoaded(AdListener.java:14)
       at com.google.android.gms.internal.ads.zzvx.onAdLoaded(Unknown Source:10)
       at com.google.android.gms.internal.ads.zzxb.dispatchTransaction(Unknown Source:11)
       at com.google.android.gms.internal.ads.zzex.onTransact(Unknown Source:12)
       at android.os.Binder.transact(Binder.java:499)
       at og.b(:com.google.android.gms.dynamite_adsdynamite@15090051@15.0.90 (040408-231259764):14)
       at com.google.android.gms.ads.internal.client.ac.c(:com.google.android.gms.dynamite_adsdynamite@15090051@15.0.90 (040408-231259764):10)
       at com.google.android.gms.ads.internal.a.c(:com.google.android.gms.dynamite_adsdynamite@15090051@15.0.90 (040408-231259764):321)
       at com.google.android.gms.ads.internal.a.q(:com.google.android.gms.dynamite_adsdynamite@15090051@15.0.90 (040408-231259764):316)
       at com.google.android.gms.ads.internal.h.q(:com.google.android.gms.dynamite_adsdynamite@15090051@15.0.90 (040408-231259764):18)
       at com.google.android.gms.ads.internal.an.q(:com.google.android.gms.dynamite_adsdynamite@15090051@15.0.90 (040408-231259764):207)
       at com.google.android.gms.ads.internal.a.b(:com.google.android.gms.dynamite_adsdynamite@15090051@15.0.90 (040408-231259764):177)
       at com.google.android.gms.ads.internal.c.b(:com.google.android.gms.dynamite_adsdynamite@15090051@15.0.90 (040408-231259764):44)
       at com.google.android.gms.ads.internal.renderer.a.a(:com.google.android.gms.dynamite_adsdynamite@15090051@15.0.90 (040408-231259764):25)
       at com.google.android.gms.ads.internal.renderer.a.a(:com.google.android.gms.dynamite_adsdynamite@15090051@15.0.90 (040408-231259764):10)
       at com.google.android.gms.ads.internal.webview.j.p(:com.google.android.gms.dynamite_adsdynamite@15090051@15.0.90 (040408-231259764):110)
       at com.google.android.gms.ads.internal.webview.j.onPageFinished(:com.google.android.gms.dynamite_adsdynamite@15090051@15.0.90 (040408-231259764):83)
       at xH.c(SourceFile:222)
       at ayK.handleMessage(SourceFile:72)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:156)
       at android.app.ActivityThread.main(ActivityThread.java:6523)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

It's not always, just few users affected (about 1%). Different android versions (4.4.2, 7.0, 8.0.0)

**Comment by petarov** [comment]
Hi! On my side it's:

```java
2019-03-28 20:37:41.343 22455-22551/my.test.app E/PluginManager: Uncaught exception from plugin
    java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.ArrayList.forEach(java.util.function.Consumer)' on a null object reference
        at admob.plugin.AdMob.execute(AdMob.java:49)
        at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
        at org.apache.cordova.PluginManager.exec(PluginManager.java:132)
        at com.getcapacitor.MessageHandler.callCordovaPluginMethod(MessageHandler.java:73)
        at com.getcapacitor.MessageHandler.postMessage(MessageHandler.java:46)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:325)
        at android.os.Looper.loop(Looper.java:142)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

I don't know the code, but I don't understand why is [this part in the code](https://github.com/admob-plus/admob-plus/blob/master/packages/cordova/src/android/AdMob.java#L52) being set to `null` in PR #81. It doesn't seem right at first. 😕

**Comment by bardgr** [comment]
I have also 600% more crashes because of bug #77 and #80 in comparison with admob free

**Comment by steebchen** [comment]
Not stale. cc @ratson
